/// Copyright (c) Theophilus Eriata. All Rights Reserved.

#pragma once

#include <Foundation/Basics.h>
#include <Foundation/Basics/Platform/Windows/HResultUtils.h>
#include <Foundation/Basics/Platform/Windows/IncludeWindows.h>
#include <Foundation/Logging/Log.h>

#include <directx/d3d12.h>
#include <dxguids/dxguids.h>

#include <GraphicsFoundation/Utilities/GraphicsUtilities.h>
#include <GraphicsFoundation/Utilities/TextureUtilities.h>

#include <GraphicsD3D12/Utilities/D3D12TypeConversions.h>

XII_DEFINE_AS_POD_TYPE(D3D12_CLEAR_VALUE);
XII_DEFINE_AS_POD_TYPE(D3D12_RAYTRACING_GEOMETRY_DESC);
XII_DEFINE_AS_POD_TYPE(D3D12_DESCRIPTOR_RANGE);
XII_DEFINE_AS_POD_TYPE(D3D12_ROOT_PARAMETER);
XII_DEFINE_AS_POD_TYPE(D3D12_STATIC_SAMPLER_DESC);
XII_DEFINE_AS_POD_TYPE(D3D12_STATE_SUBOBJECT);
XII_DEFINE_AS_POD_TYPE(D3D12_EXPORT_DESC);
XII_DEFINE_AS_POD_TYPE(D3D12_DXIL_LIBRARY_DESC);
XII_DEFINE_AS_POD_TYPE(D3D12_HIT_GROUP_DESC);
XII_DEFINE_AS_POD_TYPE(D3D12_PLACED_SUBRESOURCE_FOOTPRINT);
XII_DEFINE_AS_POD_TYPE(D3D12_RESOURCE_BARRIER);
XII_DEFINE_AS_POD_TYPE(D3D12_VIEWPORT);
XII_DEFINE_AS_POD_TYPE(D3D12_RECT);
XII_DEFINE_AS_POD_TYPE(D3D12_VERTEX_BUFFER_VIEW);
XII_DEFINE_AS_POD_TYPE(D3D12_CPU_DESCRIPTOR_HANDLE);
