#pragma once

#include <GraphicsCore/GraphicsCoreDLL.h>
#include <GraphicsCore/Pipeline/RenderGraph.h>

/// \brief Traverses the DAG-based Virtual Geometry data structure and resolves sub-pixel accurate visibility.
/// Output is a 64-bit visibility buffer (32-bit instance ID + 32-bit triangle ID).
class XII_GRAPHICSCORE_DLL xiiVisibilityBufferPass : public xiiRenderGraphPass
{
  XII_ADD_DYNAMIC_REFLECTION(xiiVisibilityBufferPass, xiiRenderGraphPass);

public:
  xiiVisibilityBufferPass();
  ~xiiVisibilityBufferPass();

  virtual bool GetRenderTargetDescriptions(const xiiView& view, const xiiArrayPtr<xiiGALTextureCreationDescription* const> inputs, xiiArrayPtr<xiiGALTextureCreationDescription> outputs) override;
  virtual void InitRenderPipelinePass(const xiiArrayPtr<xiiRenderPipelinePassConnection* const> inputs, const xiiArrayPtr<xiiRenderPipelinePassConnection* const> outputs) override;
  virtual void Execute(const xiiRenderViewContext& renderViewContext, const xiiArrayPtr<xiiRenderPipelinePassConnection* const> inputs, const xiiArrayPtr<xiiRenderPipelinePassConnection* const> outputs) override;

private:
  xiiGALPipelineStateHandle m_hVisibilityPSO;
};

/// \brief Evaluates material shading for pixels generated by the Visibility Buffer pass.
/// Reads the 64-bit visibility buffer, reconstructs the barycentrics, fetches vertex/texture data,
/// and outputs to the GBuffer or forward target.
class XII_GRAPHICSCORE_DLL xiiMaterialEvalPass : public xiiRenderGraphPass
{
  XII_ADD_DYNAMIC_REFLECTION(xiiMaterialEvalPass, xiiRenderGraphPass);

public:
  xiiMaterialEvalPass();
  ~xiiMaterialEvalPass();

  virtual bool GetRenderTargetDescriptions(const xiiView& view, const xiiArrayPtr<xiiGALTextureCreationDescription* const> inputs, xiiArrayPtr<xiiGALTextureCreationDescription> outputs) override;
  virtual void InitRenderPipelinePass(const xiiArrayPtr<xiiRenderPipelinePassConnection* const> inputs, const xiiArrayPtr<xiiRenderPipelinePassConnection* const> outputs) override;
  virtual void Execute(const xiiRenderViewContext& renderViewContext, const xiiArrayPtr<xiiRenderPipelinePassConnection* const> inputs, const xiiArrayPtr<xiiRenderPipelinePassConnection* const> outputs) override;

private:
  xiiGALPipelineStateHandle m_hMaterialEvalPSO;
};
