#include <TypeScriptPlugin/TypeScriptPluginPCH.h>

#include <Foundation/IO/FileSystem/DeferredFileWriter.h>
#include <Foundation/IO/FileSystem/FileReader.h>
#include <Foundation/IO/FileSystem/FileWriter.h>
#include <Foundation/IO/OSFile.h>
#include <TypeScriptPlugin/Components/TypeScriptComponent.h>
#include <TypeScriptPlugin/TsBinding/TsBinding.h>

xiiResult xiiTypeScriptBinding::SetupProjectCode()
{
  xiiStringBuilder sAbsPathToXIITemplate, sAbsPathToData;
  XII_SUCCEED_OR_RETURN(xiiFileSystem::ResolvePath(":plugins/TypeScript/xii-template.ts", &sAbsPathToXIITemplate, nullptr));

  sAbsPathToData = sAbsPathToXIITemplate;
  sAbsPathToData.PathParentDirectory();

  xiiStringBuilder sXIIFileContent;

  // read xii.ts
  {
    xiiFileReader fileXII;
    XII_SUCCEED_OR_RETURN(fileXII.Open(sAbsPathToXIITemplate));
    sXIIFileContent.ReadAll(fileXII);
  }

  // Remove all files from the Project/TypeScript folder that are also in Plugins/TypeScript
#if XII_ENABLED(XII_SUPPORTS_FILE_ITERATORS)
  {
    xiiStringBuilder sTargetPath;

    xiiFileSystemIterator it;
    for (it.StartSearch(sAbsPathToData, xiiFileSystemIteratorFlags::ReportFilesRecursive); it.IsValid(); it.Next())
    {
      it.GetStats().GetFullPath(sTargetPath);

      sTargetPath.MakeRelativeTo(sAbsPathToData).IgnoreResult();
      sTargetPath.Prepend(":project/TypeScript/");

      xiiFileSystem::DeleteFile(sTargetPath);
    }
  }
#endif

  RemoveAutoGeneratedCode(sXIIFileContent);

  GenerateComponentsFile(":project/TypeScript/xii/AllComponents.ts");
  InjectComponentImportExport(sXIIFileContent, "./xii/AllComponents");

  GenerateMessagesFile(":project/TypeScript/xii/AllMessages.ts");
  InjectMessageImportExport(sXIIFileContent, "./xii/AllMessages");

  GenerateEnumsFile(":project/TypeScript/xii/AllEnums.ts", s_RequiredEnums);
  GenerateEnumsFile(":project/TypeScript/xii/AllFlags.ts", s_RequiredFlags);

  InjectEnumImportExport(sXIIFileContent, "./xii/AllEnums");
  InjectFlagsImportExport(sXIIFileContent, "./xii/AllFlags");

  {
    xiiDeferredFileWriter fileOut;
    fileOut.SetOutput(":project/TypeScript/xii.ts", true);
    XII_SUCCEED_OR_RETURN(fileOut.WriteBytes(sXIIFileContent.GetData(), sXIIFileContent.GetElementCount()));
    XII_SUCCEED_OR_RETURN(fileOut.Close());
  }

  return XII_SUCCESS;
}

void xiiTypeScriptBinding::GetTsName(const xiiRTTI* pRtti, xiiStringBuilder& out_sName)
{
  out_sName = pRtti->GetTypeName();
  out_sName.TrimWordStart("xii");
}

void xiiTypeScriptBinding::GenerateComponentCode(xiiStringBuilder& out_Code, const xiiRTTI* pRtti)
{
  xiiStringBuilder sComponentType, sParentType;
  GetTsName(pRtti, sComponentType);

  GetTsName(pRtti->GetParentType(), sParentType);

  out_Code.AppendFormat("export class {0} extends {1}\n", sComponentType, sParentType);
  out_Code.Append("{\n");
  out_Code.AppendFormat("  public static GetTypeNameHash(): number { return {}; }\n", xiiHashingUtils::StringHashTo32(pRtti->GetTypeNameHash()));
  GenerateExposedFunctionsCode(out_Code, pRtti);
  GeneratePropertiesCode(out_Code, pRtti);
  out_Code.Append("}\n\n");
}

static void CreateComponentTypeList(xiiSet<const xiiRTTI*>& ref_found, xiiDynamicArray<const xiiRTTI*>& ref_sorted, const xiiRTTI* pRtti)
{
  if (ref_found.Contains(pRtti))
    return;

  if (!pRtti->IsDerivedFrom<xiiComponent>())
    return;

  if (pRtti == xiiGetStaticRTTI<xiiComponent>() || pRtti == xiiGetStaticRTTI<xiiTypeScriptComponent>())
    return;

  ref_found.Insert(pRtti);
  CreateComponentTypeList(ref_found, ref_sorted, pRtti->GetParentType());

  ref_sorted.PushBack(pRtti);
}

void xiiTypeScriptBinding::GenerateAllComponentsCode(xiiStringBuilder& out_Code)
{
  xiiSet<const xiiRTTI*>          found;
  xiiDynamicArray<const xiiRTTI*> sorted;
  sorted.Reserve(100);

  xiiHybridArray<const xiiRTTI*, 64> alphabetical;
  for (auto pRtti : xiiRTTI::GetAllTypesDerivedFrom(xiiGetStaticRTTI<xiiComponent>(), alphabetical, true))
  {
    if (pRtti == xiiGetStaticRTTI<xiiComponent>() || pRtti == xiiGetStaticRTTI<xiiTypeScriptComponent>())
      continue;

    CreateComponentTypeList(found, sorted, pRtti);
  }

  for (auto pRtti : sorted)
  {
    GenerateComponentCode(out_Code, pRtti);
  }
}

void xiiTypeScriptBinding::GenerateComponentsFile(const char* szFile)
{
  xiiStringBuilder sFileContent;

  sFileContent =
    R"(
import __GameObject = require("TypeScript/xii/GameObject")
export import GameObject = __GameObject.GameObject;

import __Component = require("TypeScript/xii/Component")
export import Component = __Component.Component;

import __Vec2 = require("TypeScript/xii/Vec2")
export import Vec2 = __Vec2.Vec2;

import __Vec3 = require("TypeScript/xii/Vec3")
export import Vec3 = __Vec3.Vec3;

import __Mat3 = require("TypeScript/xii/Mat3")
export import Mat3 = __Mat3.Mat3;

import __Mat4 = require("TypeScript/xii/Mat4")
export import Mat4 = __Mat4.Mat4;

import __Quat = require("TypeScript/xii/Quat")
export import Quat = __Quat.Quat;

import __Transform = require("TypeScript/xii/Transform")
export import Transform = __Transform.Transform;

import __Color = require("TypeScript/xii/Color")
export import Color = __Color.Color;

import __Time = require("TypeScript/xii/Time")
export import Time = __Time.Time;

import __Angle = require("TypeScript/xii/Angle")
export import Angle = __Angle.Angle;

import Enum = require("./AllEnums")
import Flags = require("./AllFlags")

declare function __CPP_ComponentProperty_get(component: Component, id: number);
declare function __CPP_ComponentProperty_set(component: Component, id: number, value);
declare function __CPP_ComponentFunction_Call(component: Component, id: number, ...args);

)";

  GenerateAllComponentsCode(sFileContent);

  xiiDeferredFileWriter file;
  file.SetOutput(szFile, true);

  file.WriteBytes(sFileContent.GetData(), sFileContent.GetElementCount()).IgnoreResult();

  if (file.Close().Failed())
  {
    xiiLog::Error("Failed to write file '{}'", szFile);
    return;
  }
}

void xiiTypeScriptBinding::InjectComponentImportExport(xiiStringBuilder& content, const char* szComponentFile)
{
  xiiSet<const xiiRTTI*>          found;
  xiiDynamicArray<const xiiRTTI*> sorted;
  sorted.Reserve(100);

  xiiHybridArray<const xiiRTTI*, 64> alphabetical;
  for (auto pRtti : xiiRTTI::GetAllTypesDerivedFrom(xiiGetStaticRTTI<xiiComponent>(), alphabetical, true))
  {
    CreateComponentTypeList(found, sorted, pRtti);
  }

  xiiStringBuilder sImportExport, sTypeName;

  sImportExport.Format(R"(import __AllComponents = require("{}")
)",
                       szComponentFile);

  for (const xiiRTTI* pRtti : sorted)
  {
    GetTsName(pRtti, sTypeName);
    sImportExport.AppendFormat("export import {0} = __AllComponents.{0};\n", sTypeName);
  }

  AppendToTextFile(content, sImportExport);
}
