#pragma once

#include <TypeScriptPlugin/TypeScriptPluginDLL.h>

#include <Core/Console/ConsoleFunction.h>
#include <Core/ResourceManager/ResourceHandle.h>
#include <Core/Scripting/DuktapeContext.h>
#include <Core/World/Declarations.h>
#include <Core/World/World.h>
#include <Foundation/Configuration/CVar.h>
#include <Foundation/Containers/HashTable.h>
#include <Foundation/Math/Declarations.h>
#include <Foundation/Types/Uuid.h>
#include <TypeScriptPlugin/Resources/ScriptCompendiumResource.h>
#include <TypeScriptPlugin/Transpiler/Transpiler.h>

class xiiWorld;
class xiiTypeScriptComponent;
struct xiiMsgTypeScriptMsgProxy;

using xiiJavaScriptResourceHandle = xiiTypedResourceHandle<class xiiJavaScriptResource>;

enum xiiTypeScriptBindingIndexProperty
{
  ComponentHandle,
  GameObjectHandle
};

class XII_TYPESCRIPTPLUGIN_DLL xiiTypeScriptBinding
{
public:
  struct TsMessageHandler
  {
    const xiiRTTI* m_pMessageType          = nullptr;
    xiiUInt32      m_uiMessageTypeNameHash = 0;
    xiiString      m_sHandlerFunc;
  };

  struct TsComponentInfo
  {
    xiiString                           m_sComponentTypeName;
    xiiHybridArray<TsMessageHandler, 4> m_MessageHandlers;
  };

  using TsComponentTypeInfo = xiiMap<xiiUuid, TsComponentInfo>::ConstIterator;

  /// \name Basics
  ///@{

public:
  xiiTypeScriptBinding();
  ~xiiTypeScriptBinding();

  xiiResult Initialize(xiiWorld& ref_world);
  xiiResult LoadComponent(const xiiUuid& typeGuid, TsComponentTypeInfo& out_typeInfo);

  xiiResult FindScriptComponentInfo(const char* szComponentType, TsComponentTypeInfo& out_typeInfo);

  void RegisterMessageHandlersForComponentType(const char* szComponent, const xiiUuid& componentType);

  XII_ALWAYS_INLINE xiiDuktapeContext& GetDukTapeContext() { return m_Duk; }
  XII_ALWAYS_INLINE duk_context* GetDukContext() { return m_Duk.GetContext(); }

  void Update();

private:
  static void GetTsName(const xiiRTTI* pRtti, xiiStringBuilder& out_sName);

  xiiDuktapeContext                 m_Duk;
  bool                              m_bInitialized = false;
  xiiMap<xiiUuid, bool>             m_LoadedComponents;
  xiiScriptCompendiumResourceHandle m_hScriptCompendium;

  ///@}
  /// \name Typescript Code Generation
  ///@{
public:
  static xiiResult SetupProjectCode();

private:
  static void GenerateComponentCode(xiiStringBuilder& out_Code, const xiiRTTI* pRtti);
  static void GenerateExposedFunctionsCode(xiiStringBuilder& out_Code, const xiiRTTI* pRtti);
  static void GeneratePropertiesCode(xiiStringBuilder& out_Code, const xiiRTTI* pRtti);
  static void GenerateAllComponentsCode(xiiStringBuilder& out_Code);
  static void GenerateComponentsFile(const char* szFile);
  static void InjectComponentImportExport(xiiStringBuilder& content, const char* szComponentFile);
  static void InjectMessageImportExport(xiiStringBuilder& content, const char* szComponentFile);
  static void GenerateEnumsFile(const char* szFile, const xiiSet<const xiiRTTI*>& items);
  static void InjectEnumImportExport(xiiStringBuilder& content, const char* szEnumFile);
  static void InjectFlagsImportExport(xiiStringBuilder& content, const char* szEnumFile);
  static void GenerateConstructorString(xiiStringBuilder& out_String, const xiiVariant& value);

  static void RemoveAutoGeneratedCode(xiiStringBuilder& content);
  static void AppendToTextFile(xiiStringBuilder& content, xiiStringView text);

  static xiiSet<const xiiRTTI*> s_RequiredEnums;
  static xiiSet<const xiiRTTI*> s_RequiredFlags;

  ///@}
  /// \name Function Binding
  ///@{

public:
  struct FunctionBinding
  {
    xiiAbstractFunctionProperty* m_pFunc = nullptr;
  };

  static const FunctionBinding* FindFunctionBinding(xiiUInt32 uiFunctionHash);

private:
  static xiiUInt32   ComputeFunctionBindingHash(const xiiRTTI* pType, xiiAbstractFunctionProperty* pFunc);
  static void        SetupRttiFunctionBindings();
  static const char* TsType(const xiiRTTI* pRtti);
  static int         __CPP_Binding_RegisterMessageHandler(duk_context* pDuk);

  static xiiHashTable<xiiUInt32, FunctionBinding> s_BoundFunctions;


  ///@}
  /// \name Property Binding
  ///@{

public:
  struct PropertyBinding
  {
    xiiAbstractMemberProperty* m_pMember = nullptr;
  };

  static const PropertyBinding* FindPropertyBinding(xiiUInt32 uiHash);

  static void SyncXIIObjectToTsObject(duk_context* pDuk, const xiiRTTI* pRtti, const void* pObject, xiiInt32 iObjIdx);
  static void SyncTsObjectXIITsObject(duk_context* pDuk, const xiiRTTI* pRtti, void* pObject, xiiInt32 iObjIdx);

private:
  static xiiUInt32 ComputePropertyBindingHash(const xiiRTTI* pType, xiiAbstractMemberProperty* pMember);
  static void      SetupRttiPropertyBindings();

  static xiiHashTable<xiiUInt32, PropertyBinding> s_BoundProperties;

  ///@}
  /// \name Message Binding
  ///@{

public:
  xiiUniquePtr<xiiMessage> MessageFromParameter(duk_context* pDuk, xiiInt32 iObjIdx, xiiTime delay);
  static void              DukPutMessage(duk_context* pDuk, const xiiMessage& msg);

  bool HasMessageHandler(const TsComponentTypeInfo& typeInfo, const xiiRTTI* pMsgRtti) const;
  bool DeliverMessage(const TsComponentTypeInfo& typeInfo, xiiTypeScriptComponent* pComponent, xiiMessage& ref_msg, bool bSynchronizeAfterwards);
  bool DeliverTsMessage(const TsComponentTypeInfo& typeInfo, xiiTypeScriptComponent* pComponent, const xiiMsgTypeScriptMsgProxy& msg);

private:
  static void GenerateMessagesFile(const char* szFile);
  static void GenerateAllMessagesCode(xiiStringBuilder& out_Code);
  static void GenerateMessageCode(xiiStringBuilder& out_Code, const xiiRTTI* pRtti);
  static void GenerateMessagePropertiesCode(xiiStringBuilder& out_Code, const xiiRTTI* pRtti);

  xiiInt32                         m_iMsgDeliveryRecursion = 0;
  xiiUuid                          m_CurrentTsMsgHandlerRegistrator;
  xiiMap<xiiUuid, TsComponentInfo> m_TsComponentTypes;


  ///@}
  /// \name Modules
  ///@{
private:
  static int DukSearchModule(duk_context* pDuk);

  ///@}
  /// \name Initialization
  ///@{
private:
  xiiResult Init_RequireModules();
  xiiResult Init_Log();
  xiiResult Init_Utils();
  xiiResult Init_Time();
  xiiResult Init_GameObject();
  xiiResult Init_Component();
  xiiResult Init_World();
  xiiResult Init_Clock();
  xiiResult Init_Random();
  xiiResult Init_FunctionBinding();
  xiiResult Init_PropertyBinding();
  xiiResult Init_Debug();
  xiiResult Init_Physics();


  ///@}
  /// \name xiiWorld
  ///@{
public:
  static xiiWorld*             RetrieveWorld(duk_context* pDuk);
  static xiiTypeScriptBinding* RetrieveBinding(duk_context* pDuk);

  xiiWorld* GetWorld() { return m_pWorld; }

private:
  void StoreWorld(xiiWorld* pWorld);

  xiiWorld*                                    m_pWorld = nullptr;
  static xiiHashTable<duk_context*, xiiWorld*> s_DukToWorld;

  ///@}
  /// \name xiiGameObject
  ///@{
public:
  static xiiGameObjectHandle RetrieveGameObjectHandle(duk_context* pDuk, xiiInt32 iObjIdx = 0 /* use 0, if the game object is passed in as the 'this' object (first parameter) */);
  static xiiGameObject*      ExpectGameObject(duk_context* pDuk, xiiInt32 iObjIdx = 0 /* use 0, if the game object is passed in as the 'this' object (first parameter) */);
  bool                       DukPutGameObject(const xiiGameObjectHandle& hObject);
  void                       DukPutGameObject(const xiiGameObject* pObject);

  ///@}
  /// \name Components
  ///@{
public:
  void                      DukPutComponentObject(xiiComponent* pComponent);
  static xiiComponentHandle RetrieveComponentHandle(duk_context* pDuk, xiiInt32 iObjIdx = 0 /* use 0, if the component is passed in as the 'this' object (first parameter) */);

  template <typename ComponentType>
  static ComponentType* ExpectComponent(duk_context* pDuk, xiiInt32 iObjIdx = 0 /* use 0, if the game object is passed in as the 'this' object (first parameter) */);

  ///@}
  /// \name Math
  ///@{

  static void    PushVec2(duk_context* pDuk, const xiiVec2& value);
  static void    SetVec2(duk_context* pDuk, xiiInt32 iObjIdx, const xiiVec2& value);
  static void    SetVec2Property(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiVec2& value);
  static xiiVec2 GetVec2(duk_context* pDuk, xiiInt32 iObjIdx, const xiiVec2& vFallback = xiiVec2::ZeroVector());
  static xiiVec2 GetVec2Property(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiVec2& vFallback = xiiVec2::ZeroVector());

  static void    PushVec3(duk_context* pDuk, const xiiVec3& value);
  static void    SetVec3(duk_context* pDuk, xiiInt32 iObjIdx, const xiiVec3& value);
  static void    SetVec3Property(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiVec3& value);
  static xiiVec3 GetVec3(duk_context* pDuk, xiiInt32 iObjIdx, const xiiVec3& vFallback = xiiVec3::ZeroVector());
  static xiiVec3 GetVec3Property(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiVec3& vFallback = xiiVec3::ZeroVector());

  static void    PushMat3(duk_context* pDuk, const xiiMat3& value);
  static void    SetMat3(duk_context* pDuk, xiiInt32 iObjIdx, const xiiMat3& value);
  static void    SetMat3Property(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiMat3& value);
  static xiiMat3 GetMat3(duk_context* pDuk, xiiInt32 iObjIdx, const xiiMat3& mFallback = xiiMat3::IdentityMatrix());
  static xiiMat3 GetMat3Property(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiMat3& mFallback = xiiMat3::IdentityMatrix());

  static void    PushMat4(duk_context* pDuk, const xiiMat4& value);
  static void    SetMat4(duk_context* pDuk, xiiInt32 iObjIdx, const xiiMat4& value);
  static void    SetMat4Property(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiMat4& value);
  static xiiMat4 GetMat4(duk_context* pDuk, xiiInt32 iObjIdx, const xiiMat4& mFallback = xiiMat4::IdentityMatrix());
  static xiiMat4 GetMat4Property(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiMat4& mFallback = xiiMat4::IdentityMatrix());

  static void    PushQuat(duk_context* pDuk, const xiiQuat& value);
  static void    SetQuat(duk_context* pDuk, xiiInt32 iObjIdx, const xiiQuat& value);
  static void    SetQuatProperty(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiQuat& value);
  static xiiQuat GetQuat(duk_context* pDuk, xiiInt32 iObjIdx, xiiQuat qFallback = xiiQuat::IdentityQuaternion());
  static xiiQuat GetQuatProperty(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, xiiQuat qFallback = xiiQuat::IdentityQuaternion());

  static void     PushColor(duk_context* pDuk, const xiiColor& value);
  static void     SetColor(duk_context* pDuk, xiiInt32 iObjIdx, const xiiColor& value);
  static void     SetColorProperty(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiColor& value);
  static xiiColor GetColor(duk_context* pDuk, xiiInt32 iObjIdx, const xiiColor& fallback = xiiColor::White);
  static xiiColor GetColorProperty(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiColor& fallback = xiiColor::White);

  static void         PushTransform(duk_context* pDuk, const xiiTransform& value);
  static void         SetTransform(duk_context* pDuk, xiiInt32 iObjIdx, const xiiTransform& value);
  static void         SetTransformProperty(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiTransform& value);
  static xiiTransform GetTransform(duk_context* pDuk, xiiInt32 iObjIdx, const xiiTransform& fallback = xiiTransform::IdentityTransform());
  static xiiTransform GetTransformProperty(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiTransform& fallback = xiiTransform::IdentityTransform());

  static void       PushVariant(duk_context* pDuk, const xiiVariant& value);
  static void       SetVariantProperty(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiVariant& value);
  static xiiVariant GetVariant(duk_context* pDuk, xiiInt32 iObjIdx, const xiiRTTI* pType);
  static xiiVariant GetVariantProperty(duk_context* pDuk, const char* szPropertyName, xiiInt32 iObjIdx, const xiiRTTI* pType);

  ///@}
  /// \name Debug
  ///@{

public:
  xiiMap<xiiString, xiiUniquePtr<xiiCVar>> m_CVars;

  struct ConsoleFuncBinding2
  {
    xiiComponentHandle m_hOwner;
    xiiUInt32          m_uiFuncStashIdx = 0;
  };

  struct ConsoleFuncBinding
  {
    xiiUniquePtr<xiiConsoleFunctionBase>   m_pFunc;
    xiiHybridArray<ConsoleFuncBinding2, 4> m_Registered;
  };

  xiiMap<xiiString, ConsoleFuncBinding> m_ConsoleFuncs;

  void StoreConsoleFuncCall(xiiConsoleFunctionBase* pFunc, const xiiArrayPtr<xiiVariant>& params);

private:
  void ExecuteConsoleFuncs();

  struct ConsoleFuncCall
  {
    xiiConsoleFunctionBase*       m_pFunc;
    xiiHybridArray<xiiVariant, 4> m_Arguments;
  };

  xiiHybridArray<ConsoleFuncCall, 4> m_CFuncCalls;

  ///@}
  /// \name C++ Object Registration
  ///@{
public:
  bool      RegisterGameObject(xiiGameObjectHandle hHandle, xiiUInt32& out_uiStashIdx);
  xiiResult RegisterComponent(const char* szTypeName, xiiComponentHandle hHandle, xiiUInt32& out_uiStashIdx, bool bIsNativeComponent);

  /// \brief Removes dead GameObject and Component references from the DukTape stash.
  void CleanupStash(xiiUInt32 uiNumIterations);

  xiiUInt32 AcquireStashObjIndex();
  void      ReleaseStashObjIndex(xiiUInt32 uiIdx);

private:
  static void StoreReferenceInStash(duk_context* pDuk, xiiUInt32 uiStashIdx);
  static bool DukPushStashObject(duk_context* pDuk, xiiUInt32 uiStashIdx);

  static constexpr xiiUInt32                       c_uiMaxMsgStash      = 512;
  static constexpr xiiUInt32                       c_uiFirstStashMsgIdx = 512;
  static constexpr xiiUInt32                       c_uiLastStashMsgIdx  = c_uiFirstStashMsgIdx + c_uiFirstStashMsgIdx;
  static constexpr xiiUInt32                       c_uiFirstStashObjIdx = c_uiLastStashMsgIdx;
  xiiUInt32                                        m_uiNextStashMsgIdx  = c_uiFirstStashMsgIdx;
  xiiUInt32                                        m_uiNextStashObjIdx  = c_uiFirstStashObjIdx;
  xiiMap<xiiGameObjectHandle, xiiUInt32>           m_GameObjectToStashIdx;
  xiiMap<xiiComponentHandle, xiiUInt32>            m_ComponentToStashIdx;
  xiiDeque<xiiUInt32>                              m_FreeStashObjIdx;
  xiiMap<xiiGameObjectHandle, xiiUInt32>::Iterator m_LastCleanupObj;
  xiiMap<xiiComponentHandle, xiiUInt32>::Iterator  m_LastCleanupComp;
  xiiDynamicArray<xiiTime>                         m_StashedMsgDelivery;

  ///@}
};

template <typename ComponentType>
ComponentType* xiiTypeScriptBinding::ExpectComponent(duk_context* pDuk, xiiInt32 iObjIdx /*= 0 */)
{
  xiiComponentHandle hOwnHandle = xiiTypeScriptBinding::RetrieveComponentHandle(pDuk, iObjIdx);

  ComponentType* pComponent = nullptr;
  xiiWorld*      pWorld     = xiiTypeScriptBinding::RetrieveWorld(pDuk);
  XII_VERIFY(pWorld->TryGetComponent(hOwnHandle, pComponent), "Invalid component parameter");

  return pComponent;
}
