#include <TypeScriptPlugin/TypeScriptPluginPCH.h>

#include <Foundation/Containers/ArrayMap.h>
#include <Foundation/IO/FileSystem/DeferredFileWriter.h>
#include <Foundation/IO/FileSystem/FileReader.h>
#include <Foundation/IO/FileSystem/FileWriter.h>
#include <TypeScriptPlugin/TsBinding/TsBinding.h>

void xiiTypeScriptBinding::RemoveAutoGeneratedCode(xiiStringBuilder& content)
{
  xiiStringBuilder sFinal;

  {
    if (const char* szAutoGen = content.FindSubString("// AUTO-GENERATED"))
    {
      sFinal.SetSubString_FromTo(content.GetData(), szAutoGen);
    }
    else
    {
      sFinal = content;
    }

    sFinal.Trim(" \t\n\r");
    sFinal.Append("\n\n");
  }

  content = sFinal;
}

void xiiTypeScriptBinding::AppendToTextFile(xiiStringBuilder& content, xiiStringView text)
{
  content.Append("\n\n// AUTO-GENERATED\n");
  content.Append(text);
  content.Append("\n");
}

void xiiTypeScriptBinding::GenerateEnumsFile(const char* szFile, const xiiSet<const xiiRTTI*>& items)
{
  xiiArrayMap<xiiString, const xiiRTTI*> sortedItems;
  xiiStringBuilder                       sType, sName;

  for (const xiiRTTI* pRtti : items)
  {
    if (pRtti->GetProperties().IsEmpty())
      continue;

    sName = pRtti->GetTypeName();
    sName.TrimWordStart("xii");

    sortedItems.Insert(sName, pRtti);
  }

  sortedItems.Sort();

  xiiStringBuilder sFileContent = "// AUTO-GENERATED FILE\n\n";

  for (xiiUInt32 i = 0; i < sortedItems.GetCount(); ++i)
  {
    const xiiRTTI* pRtti = sortedItems.GetValue(i);

    sType.Format("export enum {0} { ", sortedItems.GetKey(i));

    for (auto pProp : pRtti->GetProperties().GetSubArray(1))
    {
      if (pProp->GetCategory() == xiiPropertyCategory::Constant)
      {
        const xiiVariant value  = static_cast<const xiiAbstractConstantProperty*>(pProp)->GetConstant();
        const xiiInt64   iValue = value.ConvertTo<xiiInt64>();

        sType.AppendFormat(" {0} = {1},", xiiStringUtils::FindLastSubString(pProp->GetPropertyName(), "::") + 2, iValue);
      }
    }

    sType.Shrink(0, 1);
    sType.Append(" }\n");

    sFileContent.Append(sType.GetView());
  }

  xiiDeferredFileWriter file;
  file.SetOutput(szFile, true);

  file.WriteBytes(sFileContent.GetData(), sFileContent.GetElementCount()).IgnoreResult();

  if (file.Close().Failed())
  {
    xiiLog::Error("Failed to write file '{}'", szFile);
    return;
  }
}

void xiiTypeScriptBinding::InjectEnumImportExport(xiiStringBuilder& content, const char* szEnumFile)
{
  xiiStringBuilder sImportExport, sTypeName;

  sImportExport.Format("import __AllEnums = require(\"{}\")\n", szEnumFile);

  xiiDynamicArray<const xiiRTTI*> sorted;
  sorted.Reserve(s_RequiredEnums.GetCount());
  for (const xiiRTTI* pRtti : s_RequiredEnums)
  {
    sorted.PushBack(pRtti);
  }
  sorted.Sort([](const xiiRTTI* r1, const xiiRTTI* r2) -> bool { return xiiStringUtils::Compare(r1->GetTypeName(), r2->GetTypeName()) < 0; });

  for (const xiiRTTI* pRtti : sorted)
  {
    GetTsName(pRtti, sTypeName);
    sImportExport.AppendFormat("export import {0} = __AllEnums.{0};\n", sTypeName);
  }

  AppendToTextFile(content, sImportExport);
}

void xiiTypeScriptBinding::InjectFlagsImportExport(xiiStringBuilder& content, const char* szFlagsFile)
{
  xiiStringBuilder sImportExport, sTypeName;

  sImportExport.Format("import __AllFlags = require(\"{}\")\n", szFlagsFile);

  xiiDynamicArray<const xiiRTTI*> sorted;
  sorted.Reserve(s_RequiredFlags.GetCount());
  for (const xiiRTTI* pRtti : s_RequiredFlags)
  {
    sorted.PushBack(pRtti);
  }
  sorted.Sort([](const xiiRTTI* r1, const xiiRTTI* r2) -> bool { return xiiStringUtils::Compare(r1->GetTypeName(), r2->GetTypeName()) < 0; });

  for (const xiiRTTI* pRtti : sorted)
  {
    GetTsName(pRtti, sTypeName);
    sImportExport.AppendFormat("export import {0} = __AllFlags.{0};\n", sTypeName);
  }

  AppendToTextFile(content, sImportExport);
}
