"Area: Graphics":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/Engine/GraphicsFoundation/**",
              "Source/Engine/GraphicsVulkan/**",
              "Source/Engine/GraphicsCore/**",
              "Source/Engine/ShaderCompilerSPIRV/**",
              "Data/Base/Shaders/**"
            ]

"Area: Compute":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/Engine/Foundation/Threading/**",
              "Source/Engine/Foundation/SimdMath/**"
            ]

"Area: Core":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/Engine/Foundation/**",
              "Source/Engine/Core/**"
            ]

"Area: I/O":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/Engine/Foundation/IO/**",
              "Source/Engine/Foundation/Serialization/**"
            ]

"Area: UI":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/Tools/Libs/GuiFoundation/**",
              "Source/Editor/EditorFramework/GuiFoundation/**",
              "Source/ThirdParty/ads/**"
            ]

"Area: Scripting":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/Engine/Core/Scripting/**",
              "Source/EnginePlugins/VisualScriptPlugin/**",
              "Source/EditorPlugins/VisualScript/**",
              "Source/ThirdParty/Lua/**"
            ]

"Area: Platform":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/Engine/Foundation/Basics/**",
              "Source/Engine/Foundation/Platform/**",
              "Source/Engine/Core/Platform/**",
              "Source/Engine/Core/Input/**",
              "Source/Engine/Core/System/**",
              "Data/Platform/**"
            ]

"Area: Asset Pipeline":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Data/Base/**",
              "Data/UnitTests/**",
              "Data/Samples/**",
              "Data/Plugins/**"
            ]

"Area: Build System":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/BuildSystem/**",
              "**/CMakeLists.txt",
              "**/init.cmake",
              "**/finalize.cmake",
              "CMakeLists.txt",
              "CMakePresets.json",
              "CMakeSettings.json",
              "xiiCMakeConfig.cmake",
              "Generate.ps1",
              "Generate.sh",
              "GenerateWin64vs2022.bat",
              "cgmanifest.json",
              "version.txt",
              "launch.vs.json",
            ]

"Area: Editor":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              "Source/Editor/**",
            ]

"GitHub":
  - all:
      - changed-files:
          - any-glob-to-any-file: [
              ".github/**"
            ]
