# Copyright (c) Theophilus Eriata. All Rights Reserved.

set_property(GLOBAL PROPERTY XII_BUILDTYPENAME_DEBUG "Debug")
set_property(GLOBAL PROPERTY XII_BUILDTYPENAME_DEV "Dev")
set_property(GLOBAL PROPERTY XII_BUILDTYPENAME_RELEASE "Shipping")

set_property(GLOBAL PROPERTY XII_BUILDTYPENAME_DEBUG_UPPER "DEBUG")
set_property(GLOBAL PROPERTY XII_BUILDTYPENAME_DEV_UPPER "DEV")
set_property(GLOBAL PROPERTY XII_BUILDTYPENAME_RELEASE_UPPER "SHIPPING")

set_property(GLOBAL PROPERTY XII_DEV_BUILD_LINKERFLAGS "DEBUG")

set_property(GLOBAL PROPERTY XII_CMAKE_RELPATH "Source/BuildSystem/CMake")
set_property(GLOBAL PROPERTY XII_CMAKE_RELPATH_CODE "Source")

set_property(GLOBAL PROPERTY XII_CONFIG_PRECOMPILED_PATH "Data/Tools/Precompiled")
set_property(GLOBAL PROPERTY XII_CONFIG_PATH_7ZA "Data/Tools/Precompiled/7z.exe")

set_property(GLOBAL PROPERTY XII_CONFIG_QT_WINX64_VERSION "Qt6-6.11.0-vs144-x64")
set_property(GLOBAL PROPERTY XII_CONFIG_QT_WINX64_URL "https://github.com/XII-Technologies/PrecompiledTools/releases/download/Qt6-6.11.0-vs144-x64/Qt6-6.11.0-vs144-x64.7z")

set_property(GLOBAL PROPERTY XII_CONFIG_DIRECTXSHADERCOMPILER_LINUXX64_VERSION "1.8.2505.1")
set_property(GLOBAL PROPERTY XII_CONFIG_DIRECTXSHADERCOMPILER_LINUXX64_URL "https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2505.1/linux_dxc_2025_07_14.x86_64.tar.gz")
set_property(GLOBAL PROPERTY XII_CONFIG_DIRECTXSHADERCOMPILER_WINX64_VERSION "1.8.2505.1")
set_property(GLOBAL PROPERTY XII_CONFIG_DIRECTXSHADERCOMPILER_WINX64_URL "https://github.com/microsoft/DirectXShaderCompiler/releases/download/v1.8.2505.1/dxc_2025_07_14.zip")
