
#include <ShaderCompiler/ShaderCompilerPCH.h>

#if VULKAN_SUPPORTED

#  include <DiligentCore/Common/interface/DataBlobImpl.hpp>
#  include <DiligentCore/Graphics/GraphicsEngine/include/EngineMemory.h>
#  include <DiligentCore/Graphics/ShaderTools/include/DXCompiler.hpp>
#  include <DiligentCore/Graphics/ShaderTools/include/HLSLUtils.hpp>
#  include <DiligentCore/Graphics/ShaderTools/include/SPIRVShaderResources.hpp>
#  include <DiligentCore/Graphics/ShaderTools/include/ShaderToolsCommon.hpp>

#  include <ShaderCompiler/Implementation/Vulkan/ShaderCompilerVulkan.h>
#  include <ShaderCompiler/ShaderCompiler.h>
#  include <ShaderCompiler/ShaderMetadata.h>

#  if !DILIGENT_NO_GLSLANG
#    include <DiligentCore/Graphics/ShaderTools/include/GLSLangUtils.hpp>
#  endif

#  if !DILIGENT_NO_HLSL
#    include <DiligentCore/Graphics/ShaderTools/include/SPIRVTools.hpp>
#  else
#    error Diligent Core must be built with HLSL support enabled.
#  endif

#  include "dxc/DxilContainer/DxilContainer.h"

constexpr xiiUInt32 VK_API_VERSION_1_1 = (1u << 22) | (1u << 12);
constexpr xiiUInt32 VK_API_VERSION_1_2 = (1u << 22) | (2u << 12);

std::unique_ptr<Diligent::IDXCompiler> g_pDXCompilerVulkan = nullptr;

xiiResult xiiShaderCompilerVulkan::CompileShader(const char* szFile, const char* szSource, bool bDebug, xiiGALShaderStage::Enum Stage, Diligent::ShaderCreateInfo& shaderCreateInfo, const char* szProfile, const char* szEntryPoint, xiiDynamicArray<xiiUInt8>& out_ByteCode, std::vector<xiiUInt32>& out_SpirvOutput)
{
  auto InitializeCompiler = [this](std::unique_ptr<Diligent::IDXCompiler>& pCompiler) -> xiiResult {
    if (pCompiler != nullptr)
      return XII_SUCCESS;

    pCompiler = Diligent::CreateDXCompiler(Diligent::DXCompilerTarget::Vulkan, VK_API_VERSION_1_2, nullptr);

    if (pCompiler == nullptr)
    {
      xiiLog::Error("Failed to create DX Compiler");
      return XII_FAILURE;
    }
    return XII_SUCCESS;
  };

  XII_SUCCEED_OR_RETURN(InitializeCompiler(g_pDXCompilerVulkan));

  out_ByteCode.Clear();

  const char*      szCompileSource = szSource;
  xiiStringBuilder sDebugSource;

  xiiDynamicArray<const char*> args;

  if (bDebug)
  {
    // In debug mode we need to remove '#line' as any shader debugger won't work with them.
    sDebugSource = szSource;
    sDebugSource.ReplaceAll("#line ", "//line ");
    szCompileSource = sDebugSource;

    args.PushBack("-Zi"); // Enable debug information.
    args.PushBack("-Od"); // Disable optimization
  }
  else
  {
    args.PushBack("-O3"); // Optimization Level 3
  }

  xiiComPtr<IDxcBlob> pByteCode;

  shaderCreateInfo.EntryPoint      = szEntryPoint;
  shaderCreateInfo.CompileFlags    = Diligent::SHADER_COMPILE_FLAG_NONE;
  shaderCreateInfo.Source          = szCompileSource;
  shaderCreateInfo.SourceLength    = (xiiUInt32)strlen(szCompileSource);
  shaderCreateInfo.Desc.ShaderType = GALToDiligentShaderStage(Stage);
  shaderCreateInfo.SourceLanguage  = Diligent::SHADER_SOURCE_LANGUAGE_HLSL;
  shaderCreateInfo.HLSLVersion     = {6, 0};

  g_pDXCompilerVulkan->Compile(shaderCreateInfo, shaderCreateInfo.HLSLVersion, nullptr, pByteCode.RawDblPtr(), &out_SpirvOutput, shaderCreateInfo.ppCompilerOutput);

  if (pByteCode == nullptr)
  {
    xiiLog::Error("No shader bytecode was generated.");
    return XII_FAILURE;
  }

#  if !DILIGENT_NO_HLSL
  // SPIR-V bytecode generated from HLSL must be legalized into a valid Vulkan SPIR-V shader.
  std::vector<xiiUInt32> LegalizedSPIRV = Diligent::OptimizeSPIRV(out_SpirvOutput, spv_target_env::SPV_ENV_MAX, Diligent::SPIRV_OPTIMIZATION_FLAG_LEGALIZATION);
  if (!LegalizedSPIRV.empty())
  {
    out_SpirvOutput = std::move(LegalizedSPIRV);
  }
  else
  {
    xiiLog::Error("Failed to legalize SPIR-V shader generated from HLSL. This may result in undefined behavior.");
    return XII_FAILURE;
  }
#  else
  xiiLog::Warning("Unable to legalize SPIRV bytecode generated by DXC as the engine was built with DILIGENT_NO_HLSL option. The byte code may be invalid.");
#  endif

  out_ByteCode.SetCountUninitialized(static_cast<xiiUInt32>(pByteCode->GetBufferSize()));

  xiiMemoryUtils::Copy(out_ByteCode.GetData(), reinterpret_cast<xiiUInt8*>(pByteCode->GetBufferPointer()), out_ByteCode.GetCount());

  return XII_SUCCESS;
}

xiiResult xiiShaderCompilerVulkan::ReflectShaderStage(xiiShaderProgramCompiler::xiiShaderProgramData& inout_Data, xiiGALShaderStage::Enum Stage, Diligent::ShaderCreateInfo& shaderCreateInfo, std::vector<xiiUInt32>& spirvOutput, xiiMap<const char*, xiiGALVertexAttributeSemantic::Enum, CompareConstChar>& vertexInputMapping)
{
  XII_LOG_BLOCK("ReflectShaderStage", inout_Data.m_szSourceFile);

  auto& byteCode = inout_Data.m_StageBinary[Stage].GetByteCode();

  Diligent::ShaderDesc shaderDesc = {};
  shaderDesc.Name                 = "";
  shaderDesc.ShaderType           = GALToDiligentShaderStage(Stage);

  std::string sEntryPoint = "";

  auto& Allocator        = Diligent::GetRawAllocator();
  auto* pRawMem          = ALLOCATE(Allocator, "Memory for SPIRVShaderResources", Diligent::SPIRVShaderResources, 1);
  auto  LoadShaderInputs = Stage == xiiGALShaderStage::VertexShader;
  auto* pResources       = new (pRawMem) Diligent::SPIRVShaderResources //
    {
      Allocator,
      spirvOutput,
      shaderDesc,
      shaderDesc.UseCombinedTextureSamplers ? shaderDesc.CombinedSamplerSuffix : nullptr,
      LoadShaderInputs,
      true,
      sEntryPoint //
    };

  std::shared_ptr<Diligent::SPIRVShaderResources> pShaderResources;
  pShaderResources.reset(pResources, Diligent::STDDeleterRawMem<Diligent::SPIRVShaderResources>(Allocator));

  xiiUInt32 uiNumConstantBuffers = pShaderResources->GetNumUBs();
  for (xiiUInt32 i = 0; i < uiNumConstantBuffers; ++i)
  {
    const Diligent::ShaderCodeBufferDesc* constantBuffer = pShaderResources->GetUniformBufferDesc(i);
  }

  return XII_SUCCESS;
}

xiiShaderConstantBufferLayout* xiiShaderCompilerVulkan::ReflectConstantBufferLayout(xiiShaderStageBinary& pStageBinary, const char* szName)
{
  XII_LOG_BLOCK("Constant Buffer Layout", szName);

  return nullptr;
}

xiiResult xiiShaderCompilerVulkan::FillResourceBinding(xiiShaderStageBinary& shaderBinary, xiiShaderResourceBinding& binding)
{
  return XII_FAILURE;
}

xiiResult xiiShaderCompilerVulkan::FillSRVResourceBinding(xiiShaderStageBinary& shaderBinary, xiiShaderResourceBinding& binding)
{
  return XII_FAILURE;
}

xiiResult xiiShaderCompilerVulkan::FillUAVResourceBinding(xiiShaderStageBinary& shaderBinary, xiiShaderResourceBinding& binding)
{
  return XII_FAILURE;
}

#endif
