#include <Foundation/Application/Application.h>
#include <Foundation/CodeUtils/Tokenizer.h>
#include <Foundation/Configuration/Startup.h>
#include <Foundation/Containers/HashSet.h>
#include <Foundation/Containers/HashTable.h>
#include <Foundation/Containers/Map.h>
#include <Foundation/Containers/Set.h>
#include <Foundation/IO/FileSystem/DataDirTypeFolder.h>
#include <Foundation/IO/FileSystem/FileReader.h>
#include <Foundation/IO/FileSystem/FileSystem.h>
#include <Foundation/IO/JSONReader.h>
#include <Foundation/Logging/ConsoleWriter.h>
#include <Foundation/Logging/HTMLWriter.h>
#include <Foundation/Logging/Log.h>
#include <Foundation/Logging/VisualStudioWriter.h>
#include <Foundation/Memory/StackAllocator.h>
#include <Foundation/Strings/PathUtils.h>
#include <Foundation/Strings/String.h>
#include <Foundation/Strings/StringBuilder.h>
#include <Foundation/System/SystemInformation.h>
#include <Foundation/Threading/TaskSystem.h>
#include <Foundation/Types/UniquePtr.h>

class xiiDependencyAnalysisApp;


bool g_bVerbose = false;

namespace
{
  using DependencyListType = xiiHashSet<xiiString>;

  struct CompilationUnitContext
  {
    DependencyListType                 m_dependencies;
    xiiDynamicArray<xiiString>         m_IncludeDirectories;
    xiiHashTable<xiiString, xiiString> m_includeCache;
  };
  using CompilationUnitListType = xiiHashTable<xiiString, CompilationUnitContext>;

  XII_ALWAYS_INLINE void SkipWhitespace(xiiToken& ref_token, xiiUInt32& i, const xiiDeque<xiiToken>& tokens)
  {
    while (ref_token.m_iType == xiiTokenType::Whitespace)
    {
      ref_token = tokens[++i];
    }
  }

  XII_ALWAYS_INLINE void SkipLine(xiiToken& ref_token, xiiUInt32& i, const xiiDeque<xiiToken>& tokens)
  {
    while (ref_token.m_iType != xiiTokenType::Newline && ref_token.m_iType != xiiTokenType::EndOfFile)
    {
      ref_token = tokens[++i];
    }
  }

  // Json parser for command_line.json files generated by cmake
  class CompileCommandsParser : public xiiJSONParser
  {
  public:
    struct CompileCommand
    {
      xiiString command;
      xiiString file;
    };

    void Initialize(xiiStreamReader& ref_stream)
    {
      SetInputStream(inout_stream);
    }

    xiiResult GetNextCommand(CompileCommand& out_command)
    {
      while (!m_bObjectOpen)
      {
        if (!ContinueParsing())
        {
          return XII_FAILURE;
        }
      }

      while (m_bObjectOpen)
      {
        if (!ContinueParsing())
        {
          return XII_FAILURE;
        }
      }

      out_command = m_Command;
      return XII_SUCCESS;
    }

  private:
    // Inherited via xiiJSONParser
    virtual bool OnVariable(xiiStringView sVarName) override
    {
      bool needed = false;

      if (sVarName == "file")
      {
        needed     = true;
        m_pNextVar = &m_Command.file;
      }
      else if (sVarName == "command")
      {
        needed     = true;
        m_pNextVar = &m_Command.command;
      }

      if (!needed && sVarName != "directory" && sVarName != "output")
      {
        xiiStringBuilder fmt;
        fmt.Format("Unknown variable '{0}'", sVarName);
        ParsingError(fmt.GetView(), false);
      }
      return needed;
    }

    virtual void OnReadValue(xiiStringView sValue) override
    {
      if (m_pNextVar == nullptr)
      {
        ParsingError("Unexpected value", true);
        return;
      }

      *m_pNextVar = sValue;
      m_pNextVar  = nullptr;
    }

    virtual void OnReadValue(double fValue) override
    {
    }

    virtual void OnReadValue(bool bValue) override
    {
    }

    virtual void OnReadValueNULL() override
    {
    }

    virtual void OnBeginObject() override
    {
      if (!m_bOuterArrayOpen || m_bObjectOpen)
      {
        ParsingError("Unexpected object begin", true);
        return;
      }

      m_bObjectOpen = true;
      m_Command     = {};
    }

    virtual void OnEndObject() override
    {
      if (!m_bObjectOpen)
      {
        ParsingError("Unexpected object end", true);
        return;
      }
      m_bObjectOpen = false;
    }

    virtual void OnBeginArray() override
    {
      if (!m_bOuterArrayOpen)
      {
        m_bOuterArrayOpen = true;
      }
      else
      {
        ParsingError("Unexpected array begin", true);
      }
    }

    virtual void OnEndArray() override
    {
      if (m_bOuterArrayOpen)
      {
        m_bOuterArrayOpen = false;
      }
      else
      {
        ParsingError("Unexpected array end", true);
      }
    }

    bool           m_bOuterArrayOpen = false;
    bool           m_bObjectOpen     = false;
    xiiString*     m_pNextVar        = nullptr;
    CompileCommand m_Command;
  };

  // xiiOSFile::ExistsFile is quite slow, cache the results thread local to avoid lock contetion
  struct ExistsFileCache
  {
    static thread_local xiiHashTable<xiiString, bool> m_ExistsFileCache;

    static bool ExistsFile(xiiStringView sFile)
    {
      bool existedAlready = false;
      bool returnValue    = false;
      {
        bool& result = m_ExistsFileCache.FindOrAdd(sFile, &existedAlready);
        if (!existedAlready)
        {
          result = xiiOSFile::ExistsFile(sFile);
        }
        returnValue = result;
      }
      return returnValue;
    }
  };

  thread_local xiiHashTable<xiiString, bool> ExistsFileCache::m_ExistsFileCache;

  // Task to parse a single header file
  // stores the results in the task, need to be extracted after finish using MoveOutDependencies
  class ParseHeaderFileTask : public xiiTask
  {
  public:
    ParseHeaderFileTask()
    {
      ConfigureTask("ParseHeaderFileTask", xiiTaskNesting::Maybe);
    }

    void Initialize(xiiStringView sPath)
    {
      m_sPath = sPath;
    }

    virtual void Execute() override;

    xiiStringView           GetPath() const { return m_sPath; }
    xiiHashSet<xiiString>&& MoveOutDependencies() { return std::move(m_Dependencies); }

  private:
    xiiString             m_sPath;
    xiiHashSet<xiiString> m_Dependencies;
    xiiTaskGroupID        m_TaskGroup;
  };

  // Task to collect the dependencies of a single compilation unit
  // Might need to run multiple times (call HasWorkLeft to know if it needs to be executed again)
  // Needs to spawn other tasks when HasWorkLeft returns true: see ScheduleRemainingWork
  class CollectDependenciesTask : public xiiTask
  {
  public:
    CollectDependenciesTask()
    {
      ConfigureTask("CollectDependenciesTask", xiiTaskNesting::Maybe);
    }

    void Initialize(xiiStringView sPath, CompilationUnitContext& ref_context, xiiDependencyAnalysisApp& ref_app)
    {
      m_sPath    = sPath;
      m_pContext = &ref_context;
      m_pApp     = &ref_app;
    }

    void OnParsingFinished(xiiTaskGroupID taskGroupID);

    virtual void Execute() override;

    bool HasWorkLeft() const { return m_LeftoverFiles.GetCount() > 0; }

    void ScheduleRemainingWork();

  private:
    xiiStringView                                      m_sPath;
    CompilationUnitContext*                            m_pContext = nullptr;
    xiiDependencyAnalysisApp*                          m_pApp     = nullptr;
    xiiDynamicArray<xiiSharedPtr<ParseHeaderFileTask>> m_ParseTasks;
    xiiDynamicArray<xiiString>                         m_LeftoverFiles;
    xiiTaskGroupID                                     m_ParseTaskGroup;
  };
} // namespace

/*
* This application finds all dependencies of a given compile setup.
*
* Currently requires a compile_commands.json generated with cmake targeting the clang compiler
*
* Basic flow
* - Parse the compile_command.json to find all .cpp files (compilation units)
* - Parse each compilation unit, and find all headers it includes
* - Parse all found headers and note their dependencies (storing only the unresolved paths)
* - For each compilation unit resolve all dependencies by doing a breadth first search in parallel
*   + Whenever we encounter a header file we have not seen yet, we need to parse it
* - Write out the results into a json file. For each compilation units all header dependencies will be listed.
*/
class xiiDependencyAnalysisApp : public xiiApplication
{
private:
  friend CollectDependenciesTask;

  xiiString                  m_sCompileCommandsPath;
  bool                       m_bHadErrors;
  bool                       m_bHadSeriousWarnings;
  bool                       m_bHadWarnings;
  xiiDynamicArray<xiiString> m_IgnorePatterns;
  xiiString                  m_sOutputPath;

  CompilationUnitListType                     m_CompilationUnits;
  xiiMutex                                    m_HeaderDependenciesMutex;
  xiiHashTable<xiiString, DependencyListType> m_HeaderDependencies;

  xiiMutex              m_HeaderParsingScheduledMutex;
  xiiHashSet<xiiString> m_HeaderParsingScheduled;

public:
  using SUPER = xiiApplication;

  xiiDependencyAnalysisApp() :
    xiiApplication("DependencyAnalysis")
  {
    m_bHadErrors          = false;
    m_bHadSeriousWarnings = false;
    m_bHadWarnings        = false;
  }

  /// Makes sure the apps return value reflects whether there were any errors or warnings
  static void LogInspector(const xiiLoggingEventData& eventData)
  {
    xiiDependencyAnalysisApp* app = (xiiDependencyAnalysisApp*)xiiApplication::GetApplicationInstance();

    switch (eventData.m_EventType)
    {
      case xiiLogMsgType::ErrorMsg:
        app->m_bHadErrors = true;
        break;
      case xiiLogMsgType::SeriousWarningMsg:
        app->m_bHadSeriousWarnings = true;
        break;
      case xiiLogMsgType::WarningMsg:
        app->m_bHadWarnings = true;
        break;

      default:
        break;
    }
  }


  xiiResult ParseArray(const xiiVariant& value, xiiHashSet<xiiString>& ref_dst)
  {
    if (!value.CanConvertTo<xiiVariantArray>())
    {
      xiiLog::Error("Expected array");
      return XII_FAILURE;
    }
    auto       a         = value.Get<xiiVariantArray>();
    const auto arraySize = a.GetCount();
    for (xiiUInt32 i = 0; i < arraySize; i++)
    {
      auto& el = a[i];
      if (!el.CanConvertTo<xiiString>())
      {
        xiiLog::Error("Value {0} at index {1} can not be converted to a string. Expected array of strings.", el, i);
        return XII_FAILURE;
      }
      xiiStringBuilder file = el.Get<xiiString>();
      file.ToLower();
      ref_dst.Insert(file);
    }
    return XII_SUCCESS;
  }

  virtual void AfterCoreSystemsStartup() override
  {
    xiiGlobalLog::AddLogWriter(xiiLogWriter::Console::LogMessageHandler);
    xiiGlobalLog::AddLogWriter(xiiLogWriter::VisualStudio::LogMessageHandler);
    xiiGlobalLog::AddLogWriter(LogInspector);


    xiiSystemInformation info      = xiiSystemInformation::Get();
    const xiiInt32       iCpuCores = info.GetCPUCoreCount();
    xiiTaskSystem::SetWorkerThreadCount(iCpuCores);

    if (GetArgumentCount() < 2)
    {
      xiiLog::Info("DependencyAnalysis.exe [options] path/to/compile_commands.json");
      xiiLog::Info("");
      xiiLog::Info("-i [pattern] --ignorePattern [pattern]    ignore all cpp/h files containing this pattern");
      xiiLog::Info("-v           --verbose                    enable verbose logging");
      xiiLog::Info("-o [path]    --output [path]              path to the output json file");
      xiiLog::Info("");

      xiiLog::Error("No command line arguments given.");
      return;
    }

    // Add the empty data directory to access files via absolute paths
    xiiFileSystem::AddDataDirectory("", "App", ":", xiiFileSystem::AllowWrites).IgnoreResult();

    // pass the absolute path to the directory that should be scanned as the first parameter to this application
    xiiStringBuilder sCompileCommandsPath;

    auto numArgs      = GetArgumentCount();
    auto shortIgnore  = xiiStringView("-i");
    auto longIgnore   = xiiStringView("--ignorePattern");
    auto shortVerbose = xiiStringView("-v");
    auto longVerbose  = xiiStringView("--verbose");
    auto shortOutput  = xiiStringView("-o");
    auto longOutput   = xiiStringView("--output");
    for (xiiUInt32 argi = 1; argi < numArgs; argi++)
    {
      auto arg = xiiStringView(GetArgument(argi));
      if (arg == shortIgnore || arg == longIgnore)
      {
        if (numArgs <= argi + 1)
        {
          xiiLog::Error("Missing path for {0}", arg);
          return;
        }
        xiiStringBuilder ignorePattern = GetArgument(argi + 1);
        if (ignorePattern == shortIgnore || ignorePattern == longIgnore || ignorePattern == shortIgnore || ignorePattern == longIgnore || ignorePattern == shortOutput || ignorePattern == longOutput)
        {
          xiiLog::Error("Missing path for {0} found {1} instead", arg, ignorePattern.GetView());
          return;
        }
        argi++;
        ignorePattern.MakeCleanPath();
        m_IgnorePatterns.PushBack(ignorePattern);
      }
      else if (arg == shortVerbose || arg == longVerbose)
      {
        g_bVerbose = true;
      }
      else if (arg == shortOutput || arg == longOutput)
      {
        if (!m_sOutputPath.IsEmpty())
        {
          xiiLog::Error("Output path given multiple times");
          return;
        }
        if (numArgs <= argi + 1)
        {
          xiiLog::Error("Missing path for {0}", arg);
          return;
        }
        xiiStringBuilder outputPath = GetArgument(argi + 1);
        if (outputPath == shortIgnore || outputPath == longIgnore || outputPath == shortIgnore || outputPath == longIgnore || outputPath == shortOutput || outputPath == longOutput)
        {
          xiiLog::Error("Missing path for {0} found {1} instead", arg, outputPath.GetView());
          return;
        }
        if (!outputPath.IsAbsolutePath())
        {
          outputPath = xiiOSFile::GetCurrentWorkingDirectory();
          outputPath.AppendPath(GetArgument(argi + 1));
        }
        outputPath.MakeCleanPath();
        argi++;
        m_sOutputPath = outputPath;
      }
      else
      {
        if (sCompileCommandsPath.IsEmpty())
        {
          sCompileCommandsPath = arg;
          sCompileCommandsPath.MakeCleanPath();
        }
        else
        {
          xiiLog::Error("Currently only one directory is supported for searching. Did you forget -i|--includeDir? {0}", arg);
        }
      }
    }

    if (!xiiPathUtils::IsAbsolutePath(sCompileCommandsPath.GetData()))
      xiiLog::Error("The given path is not absolute: '{0}'", sCompileCommandsPath);

    m_sCompileCommandsPath = sCompileCommandsPath;

    if (m_sOutputPath.IsEmpty())
    {
      xiiLog::Error("No output path given. Use -o or --output");
    }
  }

  virtual void BeforeCoreSystemsShutdown() override
  {
    SetReturnCode(0);

    xiiGlobalLog::RemoveLogWriter(LogInspector);
    xiiGlobalLog::RemoveLogWriter(xiiLogWriter::Console::LogMessageHandler);
    xiiGlobalLog::RemoveLogWriter(xiiLogWriter::VisualStudio::LogMessageHandler);
  }

  static xiiResult ReadEntireFile(xiiStringView sFile, xiiStringBuilder& out_sContents)
  {
    out_sContents.Clear();

    xiiFileReader File;
    if (File.Open(sFile) == XII_FAILURE)
    {
      xiiLog::Error("Could not open for reading: '{0}'", sFile);
      return XII_FAILURE;
    }

    xiiDynamicArray<xiiUInt8> FileContent;

    xiiUInt8  Temp[4024];
    xiiUInt64 uiRead = File.ReadBytes(Temp, XII_ARRAY_SIZE(Temp));

    while (uiRead > 0)
    {
      FileContent.PushBackRange(xiiArrayPtr<xiiUInt8>(Temp, (xiiUInt32)uiRead));

      uiRead = File.ReadBytes(Temp, XII_ARRAY_SIZE(Temp));
    }

    FileContent.PushBack(0);

    if (!xiiUnicodeUtils::IsValidUtf8((const char*)&FileContent[0]))
    {
      xiiLog::Error("The file \"{0}\" contains characters that are not valid Utf8. This often happens when you type special characters in "
                    "an editor that does not save the file in Utf8 encoding.",
                    sFile);
      return XII_FAILURE;
    }

    out_sContents = (const char*)&FileContent[0];

    return XII_SUCCESS;
  }

  static xiiResult FindIncludeFile(xiiStringView sPath, CompilationUnitContext& inout_context, xiiStringBuilder& out_sPath)
  {
    if (sPath.IsAbsolutePath())
    {
      out_sPath = sPath;
      out_sPath.MakeCleanPath();
      if (ExistsFileCache::ExistsFile(sPath))
      {
        return XII_SUCCESS;
      }
      else
      {
        return XII_FAILURE;
      }
    }

    for (auto& includeDir : inout_context.m_IncludeDirectories)
    {
      out_sPath = includeDir;
      out_sPath.AppendPath(sPath);
      out_sPath.MakeCleanPath();
      if (ExistsFileCache::ExistsFile(out_sPath))
      {
        return XII_SUCCESS;
      }
    }

    return XII_FAILURE;
  }

  bool IgnorePath(const xiiStringBuilder& sBuilder)
  {
    for (auto& ignore : m_IgnorePatterns)
    {
      if (sBuilder.FindSubString(ignore))
      {
        return true;
      }
    }
    return false;
  }

  void ParseCompileCommandsJson()
  {
    xiiFileReader reader;
    reader.Open(m_sCompileCommandsPath).AssertSuccess(); // TODO error handling

    CompileCommandsParser parser;
    parser.SetLogInterface(xiiLog::GetThreadLocalLogSystem());
    parser.Initialize(reader);

    xiiDynamicArray<xiiStringView> commandParts;

    xiiStringBuilder tmpPath;

    CompileCommandsParser::CompileCommand command;
    while (parser.GetNextCommand(command).Succeeded())
    {
      if (g_bVerbose)
      {
        xiiLog::Info("file: {0}", command.file);
      }
      tmpPath = command.file;
      tmpPath.MakeCleanPath();

      if (IgnorePath(tmpPath))
      {
        continue;
      }

      if (tmpPath.GetFileExtension().Compare_NoCase("cpp") != 0)
      {
        continue;
      }

      auto& context = m_CompilationUnits[tmpPath];

      xiiDynamicArray<xiiString> includeFiles;

      command.command.Split(false, commandParts, " ");
      const xiiUInt32 numParts = commandParts.GetCount();
      for (xiiUInt32 i = 0; i < numParts; i++)
      {
        auto part = commandParts[i];
        if (part.Compare_NoCase("-isystem") == 0)
        {
          i++;
          part    = commandParts[i];
          tmpPath = part;
          tmpPath.MakeCleanPath();

          if (!IgnorePath(tmpPath)) // TODO make command line parameter
          {
            if (g_bVerbose)
            {
              xiiLog::Info(tmpPath);
            }
            context.m_IncludeDirectories.PushBack(tmpPath);
          }
        }
        else if (part.TrimWordStart("-include"))
        {
          tmpPath = part;
          tmpPath.MakeCleanPath();
          if (g_bVerbose)
          {
            xiiLog::Info(tmpPath);
          }
          includeFiles.PushBack(tmpPath);
        }
        else if (part.TrimWordStart("-I"))
        {
          tmpPath = part;
          tmpPath.MakeCleanPath();
          if (!IgnorePath(tmpPath))
          {
            if (g_bVerbose)
            {
              xiiLog::Info(tmpPath);
            }
            context.m_IncludeDirectories.PushBack(tmpPath);
          }
        }
      }

      for (auto& includeFile : includeFiles)
      {
        if (FindIncludeFile(includeFile.GetView(), context, tmpPath).Succeeded())
        {
          context.m_dependencies.Insert(tmpPath);
        }
        else
        {
          if (g_bVerbose)
          {
            xiiLog::Warning("Could not find include file '{0}' specified on the command line in any include path", includeFile);
          }
        }
      }
    }
  }

  void ParseCompilationUnits()
  {
    struct CompUnit
    {
      xiiStringView           path;
      CompilationUnitContext* context;
    };
    xiiDynamicArray<CompUnit> compilationUnits;
    compilationUnits.Reserve(m_CompilationUnits.GetCount());

    for (auto& compilationUnit : m_CompilationUnits)
    {
      compilationUnits.PushBack({compilationUnit.Key().GetView(), &compilationUnit.Value()});
    }

    xiiTaskSystem::ParallelFor(
      compilationUnits.GetArrayPtr(), [this](xiiArrayPtr<CompUnit> compUnits) {
        xiiStringBuilder   tmpPath;
        DependencyListType dependencies;
        for (auto& compUnit : compUnits)
        {
          xiiStringView currentFile = compUnit.path;

          XII_LOG_BLOCK("CPP", currentFile);
          dependencies.Clear();
          FindDependencies(currentFile, dependencies);
          for (auto& dependency : dependencies)
          {
            if (!dependency.IsAbsolutePath())
            {
              if (FindIncludeFile(dependency.GetView(), *compUnit.context, tmpPath).Succeeded())
              {
                compUnit.context->m_dependencies.Insert(tmpPath);
              }
              else
              {
                if (g_bVerbose)
                {
                  xiiLog::Warning("Warning dependency '{0}' of '{1}' not found", dependency, currentFile);
                }
              }
            }
          }
        }
      },
      "ParseCompilationUnit");
  }

  void ParseHeaderFiles()
  {
    xiiStringBuilder                                   tmpPath;
    xiiDynamicArray<xiiSharedPtr<ParseHeaderFileTask>> filesToCheckTasks;

    auto taskGroup = xiiTaskSystem::CreateTaskGroup(xiiTaskPriority::EarlyThisFrame);
    for (auto& compilationUnit : m_CompilationUnits)
    {
      for (auto& dependency : compilationUnit.Value().m_dependencies)
      {
        bool existed = false;
        if (auto& dependencies = m_HeaderDependencies.FindOrAdd(dependency.GetView(), &existed); !existed)
        {
          filesToCheckTasks.PushBack(XII_DEFAULT_NEW(ParseHeaderFileTask));
          filesToCheckTasks.PeekBack()->Initialize(dependency.GetView());
          xiiTaskSystem::AddTaskToGroup(taskGroup, filesToCheckTasks.PeekBack());
        }
      }
    }

    xiiTaskSystem::StartTaskGroup(taskGroup);
    xiiTaskSystem::WaitForGroup(taskGroup);

    for (auto& task : filesToCheckTasks)
    {
      m_HeaderDependencies[task->GetPath()] = task->MoveOutDependencies();
    }
  }

  void CheckDependentFiles()
  {
    xiiDynamicArray<xiiSharedPtr<CollectDependenciesTask>> tasks;

    for (auto& compilationUnit : m_CompilationUnits)
    {
      tasks.PushBack(XII_DEFAULT_NEW(CollectDependenciesTask));
      tasks.PeekBack()->Initialize(compilationUnit.Key(), compilationUnit.Value(), *this);
    }

    const xiiUInt32 totalNumTasks = tasks.GetCount();

    // First iteration
    {
      auto group = xiiTaskSystem::CreateTaskGroup(xiiTaskPriority::EarlyThisFrame);
      for (auto& task : tasks)
      {
        xiiTaskSystem::AddTaskToGroup(group, task);
      }
      xiiTaskSystem::StartTaskGroup(group);
      xiiTaskSystem::WaitForGroup(group);
    }

    while (true)
    {
      for (xiiUInt32 i = 0; i < tasks.GetCount();)
      {
        if (tasks[i]->HasWorkLeft())
        {
          tasks[i]->ScheduleRemainingWork();
          ++i;
        }
        else
        {
          tasks.RemoveAtAndSwap(i);
        }
      }

      if (tasks.GetCount() == 0) // If none of the tasks had work left, we are done
      {
        break;
      }

      xiiLog::Info("Collecting dependencies. Remaining {0} of {1} total", tasks.GetCount(), totalNumTasks);

      xiiTaskSystem::FinishFrameTasks(); // Wait for parsing tasks to finish before doing the next round of dependency collection

      auto group = xiiTaskSystem::CreateTaskGroup(xiiTaskPriority::EarlyThisFrame);
      for (auto& task : tasks)
      {
        xiiTaskSystem::AddTaskToGroup(group, task);
      }
      xiiTaskSystem::StartTaskGroup(group);
      xiiTaskSystem::WaitForGroup(group);
    }
  }

  void WriteOutResults()
  {
    xiiFileWriter FileOut;

    if (FileOut.Open(m_sOutputPath) == XII_FAILURE)
    {
      xiiLog::Error("Could not open the file for writing: '{0}'", "results.json");
      return;
    }
    else
    {
      xiiStringBuilder json;
      json.Append("{\n");
      json.Append(" \"files\" : [\n");

      auto processFile = [this, &json](CompilationUnitListType::Iterator& file) {
        json.Append("    {\n");
        json.AppendFormat("      \"name\" : \"{0}\",\n", file.Key());
        json.Append("      \"dependencies\" :\n");
        json.Append("        [\n");

        auto count = (*file).Value().m_dependencies.GetCount();
        if (count > 0)
        {
          count--;
          auto depIt = (*file).Value().m_dependencies.GetIterator();

          for (xiiUInt32 i = 0; i < count; ++i, depIt.Next())
          {
            json.AppendFormat("       \"{0}\",\n", (*depIt).GetView());
          }
          json.AppendFormat("       \"{0}\"\n", (*depIt).GetView());
        }
        json.Append("        ]\n");
        json.Append("    }");
      };

      auto count = m_CompilationUnits.GetCount();
      if (count > 0)
      {
        count--;
        auto fileIt = m_CompilationUnits.GetIterator();
        for (xiiUInt32 i = 0; i < count; ++i, fileIt.Next())
        {
          processFile(fileIt);
          json.Append(",\n");
        }
        processFile(fileIt);
        json.Append("\n");
      }
      json.Append("  ]\n");
      json.Append("}\n");

      FileOut.WriteBytes(json.GetData(), json.GetElementCount()).AssertSuccess();
    }
  }

  static void FindDependencies(xiiStringView sCurrentFile, DependencyListType& inout_dependencies)
  {
    xiiStringBuilder fileContents;
    ReadEntireFile(sCurrentFile, fileContents).IgnoreResult();

    auto fileDir = sCurrentFile.GetFileDirectory();

    xiiTokenizer tokenizer;
    auto         dataView     = fileContents.GetView();
    auto         start        = dataView.GetStartPointer();
    auto         elementCount = dataView.GetElementCount();
    if (elementCount >= 3 && xiiUnicodeUtils::SkipUtf8Bom(start))
    {
      elementCount -= 3;
    }
    tokenizer.Tokenize(xiiArrayPtr<const xiiUInt8>(reinterpret_cast<const xiiUInt8*>(start), elementCount), xiiLog::GetThreadLocalLogSystem());

    xiiStringView hash("#");
    xiiStringView include("include");
    xiiStringView openAngleBracket("<");
    xiiStringView closeAngleBracket(">");

    auto       tokens    = tokenizer.GetTokens();
    const auto numTokens = tokens.GetCount();
    for (xiiUInt32 i = 0; i < numTokens; i++)
    {
      auto curToken = tokens[i];
      while (curToken.m_iType == xiiTokenType::Whitespace)
      {
        curToken = tokens[++i];
      }
      if (curToken.m_iType == xiiTokenType::NonIdentifier && curToken.m_DataView == hash)
      {
        do
        {
          curToken = tokens[++i];
        } while (curToken.m_iType == xiiTokenType::Whitespace);

        if (curToken.m_iType == xiiTokenType::Identifier && curToken.m_DataView == include)
        {
          auto includeToken = curToken;
          do
          {
            curToken = tokens[++i];
          } while (curToken.m_iType == xiiTokenType::Whitespace);

          if (curToken.m_iType == xiiTokenType::String1)
          {
            // #include "bla"
            xiiStringBuilder absIncludePath;
            xiiStringBuilder relativePath;
            relativePath = curToken.m_DataView;
            relativePath.Trim("\"");
            relativePath.MakeCleanPath();
            absIncludePath = fileDir;
            absIncludePath.AppendPath(relativePath);

            if (!ExistsFileCache::ExistsFile(absIncludePath))
            {
              inout_dependencies.Insert(relativePath);
            }
            else
            {
              inout_dependencies.Insert(absIncludePath);
            }
          }
          else if (curToken.m_iType == xiiTokenType::NonIdentifier && curToken.m_DataView == openAngleBracket)
          {
            // #include <bla>
            bool error      = false;
            auto startToken = curToken;
            do
            {
              curToken = tokens[++i];
              if (curToken.m_iType == xiiTokenType::Newline)
              {
                xiiLog::Error("Non-terminated '<' in #include {0} line {1}", sCurrentFile, includeToken.m_uiLine);
                error = true;
                break;
              }
            } while (curToken.m_iType != xiiTokenType::NonIdentifier || curToken.m_DataView != closeAngleBracket);

            if (error)
            {
              // in case of error skip the malformed line in hopes that we can recover from the error.
              do
              {
                curToken = tokens[++i];
              } while (curToken.m_iType != xiiTokenType::Newline);
            }
            else
            {
              xiiStringBuilder includePath;
              includePath = xiiStringView(startToken.m_DataView.GetEndPointer(), curToken.m_DataView.GetStartPointer());
              includePath.MakeCleanPath();
              inout_dependencies.Insert(includePath);
            }
          }
          else
          {
            // error
            xiiLog::Error("Can not parse #include statement in {0} line {1}", sCurrentFile, includeToken.m_uiLine);
          }
        }
        else
        {
          while (curToken.m_iType != xiiTokenType::Newline && curToken.m_iType != xiiTokenType::EndOfFile)
          {
            curToken = tokens[++i];
          }
        }
      }
      else
      {
        while (curToken.m_iType != xiiTokenType::Newline && curToken.m_iType != xiiTokenType::EndOfFile)
        {
          curToken = tokens[++i];
        }
      }
    }
  }

  virtual xiiApplication::Execution Run() override
  {
    // something basic has gone wrong
    if (m_bHadSeriousWarnings || m_bHadErrors)
      return xiiApplication::Execution::Quit;

    auto start = xiiTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      xiiLog::Info("Parse compile commands json");
    }
    ParseCompileCommandsJson();

    auto parseJsonEnd = xiiTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      xiiLog::Info("Parse compilation units");
    }
    ParseCompilationUnits();

    auto parseCompilationUnitsEnd = xiiTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      xiiLog::Info("Parse header files");
    }
    ParseHeaderFiles();

    auto parseHeaderFilesEnd = xiiTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      xiiLog::Info("Build dependencies");
    }
    CheckDependentFiles();

    auto checkDependendtFilesEnd = xiiTimestamp::CurrentTimestamp();

    if (g_bVerbose)
    {
      xiiLog::Info("Write out results");
    }
    WriteOutResults();

    auto writeOutResultsEnd = xiiTimestamp::CurrentTimestamp();

    xiiLog::Info("Time to parse compile commands json: {0}s", (parseJsonEnd - start).AsFloatInSeconds());
    xiiLog::Info("Time to parse compilation units: {0}s", (parseCompilationUnitsEnd - parseJsonEnd).AsFloatInSeconds());
    xiiLog::Info("Time to parse header files: {0}s", (parseHeaderFilesEnd - parseCompilationUnitsEnd).AsFloatInSeconds());
    xiiLog::Info("Time to build dependencies: {0}s", (checkDependendtFilesEnd - parseHeaderFilesEnd).AsFloatInSeconds());
    xiiLog::Info("Time to write out results: {0}s", (writeOutResultsEnd - checkDependendtFilesEnd).AsFloatInSeconds());
    xiiLog::Info("Total time taken: {0}s", (writeOutResultsEnd - start).AsFloatInSeconds());

    return xiiApplication::Execution::Quit;
  }
};

void ParseHeaderFileTask::Execute()
{
  xiiDependencyAnalysisApp::FindDependencies(m_sPath, m_Dependencies);
}

void CollectDependenciesTask::Execute()
{
  XII_ASSERT_DEBUG(m_pContext != nullptr && m_pApp != nullptr, "Task was not initialized properly");

  auto& compilationUnitDependencies = m_pContext->m_dependencies;

  xiiDynamicArray<xiiString> filesToCheck;
  if (m_LeftoverFiles.GetCount() > 0)
  {
    filesToCheck.Swap(m_LeftoverFiles);
    m_ParseTasks.Clear();
  }
  else
  {
    for (auto& include : compilationUnitDependencies)
    {
      filesToCheck.PushBack(include);
    }
  }

  xiiHashSet<xiiString> seenFiles;

  while (!filesToCheck.IsEmpty())
  {
    auto include = std::move(filesToCheck.PeekBack());
    filesToCheck.PopBack();

    if (seenFiles.Insert(include))
    {
      continue;
    }

    bool alreadyExisted = false;

    DependencyListType* headerDependencies = nullptr;
    if (!m_pApp->m_HeaderDependencies.TryGetValue(include.GetView(), headerDependencies))
    {
      {
        XII_LOCK(m_pApp->m_HeaderParsingScheduledMutex);
        if (!m_pApp->m_HeaderParsingScheduled.Insert(include.GetView()))
        {
          if (m_ParseTasks.GetCount() == 0)
          {
            m_ParseTaskGroup = xiiTaskSystem::CreateTaskGroup(xiiTaskPriority::EarlyThisFrame, xiiMakeDelegate(&CollectDependenciesTask::OnParsingFinished, this));
          }
          xiiSharedPtr<ParseHeaderFileTask> task = XII_DEFAULT_NEW(ParseHeaderFileTask);
          task->Initialize(include);
          xiiTaskSystem::AddTaskToGroup(m_ParseTaskGroup, task);
          m_ParseTasks.PushBack(std::move(task));
        }
      }
    }
    else
    {
      xiiStringBuilder tmpPath;
      for (auto& dependency : *headerDependencies)
      {
        if (m_pApp->FindIncludeFile(dependency.GetView(), *m_pContext, tmpPath).Succeeded())
        {
          if (!compilationUnitDependencies.Contains(tmpPath.GetView()))
          {
            compilationUnitDependencies.Insert(tmpPath);
            filesToCheck.PushBack(tmpPath);
          }
        }
        else
        {
          if (g_bVerbose)
          {
            xiiLog::Warning("Failed to find dependency '{0}' of compilation unit '{1}'", dependency, m_sPath);
          }
        }
      }
    }
  }
}

void CollectDependenciesTask::ScheduleRemainingWork()
{
  if (m_ParseTasks.GetCount() > 0)
  {
    xiiTaskSystem::StartTaskGroup(m_ParseTaskGroup);
  }
}

void CollectDependenciesTask::OnParsingFinished(xiiTaskGroupID taskGroupId)
{
  XII_LOCK(m_pApp->m_HeaderDependenciesMutex);
  for (auto& task : m_ParseTasks)
  {
    bool  alreadyExisted = false;
    auto& deps           = m_pApp->m_HeaderDependencies.FindOrAdd(task->GetPath(), &alreadyExisted);
    if (!alreadyExisted)
    {
      deps = task->MoveOutDependencies();
    }
  }
}

XII_CONSOLEAPP_ENTRY_POINT(xiiDependencyAnalysisApp);
