#include <RendererVulkan/RendererVulkanPCH.h>

XII_STATICLINK_LIBRARY(RendererVulkan)
{
  if (bReturn)
    return;

  XII_STATICLINK_REFERENCE(RendererVulkan_Context_Implementation_ContextVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Device_Implementation_DeviceVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Device_Implementation_SwapChainVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_BufferVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_FenceVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_QueryVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_RenderTargetViewVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_ResourceViewVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_TextureVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Resources_Implementation_UnorderedAccessViewVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Shader_Implementation_ShaderVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_Shader_Implementation_VertexDeclarationVulkan);
  XII_STATICLINK_REFERENCE(RendererVulkan_State_Implementation_StateVulkan);
}
