#pragma once

/// \file

#include <Foundation/Reflection/Implementation/AbstractProperty.h>
#include <Foundation/Reflection/Implementation/DynamicRTTI.h>
#include <Foundation/Reflection/Implementation/RTTI.h>
#include <Foundation/Types/Interval.h>
#include <Foundation/Types/Variant.h>

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiEnumBase);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiBitflagsBase);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiReflectedClass);

// *********************************************
// ***** Standard POD Types for Properties *****

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, bool);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, float);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, double);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiInt8);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiUInt8);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiInt16);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiUInt16);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiInt32);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiUInt32);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiInt64);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiUInt64);

// Macros won't work with 'const char*'
using xiiConstCharPtr = const char*;
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiConstCharPtr);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiTime);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiColor);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiColorBaseUB);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiColorGammaUB);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiColorLinearUB);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec2);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec3);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec4);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec2d);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec3d);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec4d);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec2I32);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec2I64);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec3I32);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec3I64);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec4I32);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec4I64);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec2U32);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec2U64);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec3U32);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec3U64);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec4U32);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVec4U64);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiQuat);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiQuatd);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiMat3);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiMat3d);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiMat4);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiMat4d);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiTransform);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiTransformd);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiBasisAxis);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiUuid);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiAngle);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiFloatInterval);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiIntInterval);

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVariant);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiString);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiUntrackedString);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiStringView);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiDataBuffer);

// **********************************************************************
// ***** Various RTTI infos that can't be put next to their classes *****

XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiTypeFlags);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiPropertyFlags);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiFunctionType);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiVariantType);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiPropertyCategory);
XII_DECLARE_REFLECTABLE_TYPE(XII_FOUNDATION_DLL, xiiComparisonOperator);
