#include <ComputeShaderHistogram/ComputeShaderHistogram.h>

#include <Core/ActorSystem/Actor.h>
#include <Core/ActorSystem/ActorManager.h>
#include <Core/ActorSystem/ActorPluginWindow.h>
#include <Core/Graphics/Geometry.h>
#include <Core/Input/InputManager.h>
#include <Core/System/Window.h>
#include <Foundation/Time/Clock.h>
#include <Foundation/Utilities/Stats.h>
#include <GameEngine/GameApplication/WindowOutputTarget.h>
#include <RendererCore/RenderContext/RenderContext.h>
#include <RendererCore/ShaderCompiler/ShaderManager.h>
#include <RendererFoundation/Device/SwapChain.h>
#include <RendererFoundation/Resources/Texture.h>

static xiiUInt32 g_uiComputeThreadGroupSize = 32;

xiiComputeShaderHistogramApp::xiiComputeShaderHistogramApp() :
  xiiGameApplication("ComputeShaderHistogram", "Data/Samples/ComputeShaderHistogram"), m_pWindow(nullptr)
{
}

xiiComputeShaderHistogramApp::~xiiComputeShaderHistogramApp() = default;

xiiApplication::Execution xiiComputeShaderHistogramApp::Run()
{
  xiiActorManager::GetSingleton()->Update();

  xiiClock::GetGlobalClock()->Update();
  Run_InputUpdate();

  m_bDirectoryModified = false;
  m_pDirectoryWatcher->EnumerateChanges(xiiMakeDelegate(&xiiComputeShaderHistogramApp::OnFileChanged, this));
  if (m_bDirectoryModified)
  {
    xiiResourceManager::ReloadAllResources(false);
  }

  xiiUInt32 uiWindowWidth  = m_pWindow->GetClientAreaSize().width;
  xiiUInt32 uiWindowHeight = m_pWindow->GetClientAreaSize().height;

  // Do the rendering
  {
    auto device = xiiGALDevice::GetDefaultDevice();

    const xiiGALSwapChain*       pPrimarySwapChain = device->GetSwapChain(m_hSwapChain);
    xiiGALRenderTargetViewHandle hBackbufferRTV    = device->GetDefaultRenderTargetView(pPrimarySwapChain->GetRenderTargets().m_hRTs[0]);

    // Before starting to render in a frame call this function
    device->BeginFrame();

    device->BeginPipeline("ComputeShaderHistogramSample", m_hSwapChain);

    xiiGALPass* pGALPass = device->BeginPass("xiiComputeShaderHistogram");

    xiiRenderContext& renderContext = *xiiRenderContext::GetDefaultInstance();

    // Constant buffer update
    {
      auto& globalConstants = renderContext.WriteGlobalConstants();
      xiiMemoryUtils::ZeroFill(&globalConstants, 1);

      globalConstants.ViewportSize = xiiVec4((float)uiWindowWidth, (float)uiWindowHeight, 1.0f / (float)uiWindowWidth, 1.0f / (float)uiWindowHeight);
      // Wrap around to prevent floating point issues. Wrap around is dividable by all whole numbers up to 11.
      globalConstants.GlobalTime = (float)xiiMath::Mod(xiiClock::GetGlobalClock()->GetAccumulatedTime().GetSeconds(), 20790.0);
      globalConstants.WorldTime  = globalConstants.GlobalTime;
    }

    xiiRectFloat viewport(0.0f, 0.0f, (float)uiWindowWidth, (float)uiWindowHeight);

    // Draw background.
    {
      xiiGALRenderingSetup renderingSetup;
      renderingSetup.m_RenderTargetSetup.SetRenderTarget(0, m_hScreenRTV);
      renderContext.BeginRendering(pGALPass, renderingSetup, viewport, "Background");

      renderContext.BindShader(m_hScreenShader);
      renderContext.BindMeshBuffer(xiiGALBufferHandle(), xiiGALBufferHandle(), nullptr, xiiGALPrimitiveTopology::Triangles, 1); // Vertices are generated by shader.
      renderContext.DrawMeshBuffer().IgnoreResult();

      // Copy screentexture contents to backbuffer.
      // (Is drawing better? Don't care, this is a one liner and needs no shader!)
      renderContext.GetCommandEncoder()->CopyTexture(device->GetBackBufferTextureFromSwapChain(m_hSwapChain), m_hScreenTexture);

      renderContext.EndRendering();
    }

    // Switch to backbuffer (so that the screen texture is no longer bound)
    {
      xiiGALRenderingSetup renderingSetup;
      renderingSetup.m_RenderTargetSetup.SetRenderTarget(0, hBackbufferRTV);
      renderContext.BeginRendering(pGALPass, renderingSetup, viewport, "Dummy");
      renderContext.EndRendering();
    }

    // Compute histogram.
    {
      renderContext.BeginCompute(pGALPass, "ComputeHistogram");

      // Reset first.
      renderContext.GetCommandEncoder()->ClearUnorderedAccessView(m_hHistogramUAV, xiiVec4U32(0, 0, 0, 0));

      renderContext.BindShader(m_hHistogramComputeShader);
      renderContext.BindTexture2D("ScreenTexture", m_hScreenSRV);
      renderContext.BindUAV("HistogramOutput", m_hHistogramUAV);
      renderContext.Dispatch(uiWindowWidth / g_uiComputeThreadGroupSize + (uiWindowWidth % g_uiComputeThreadGroupSize != 0 ? 1 : 0), uiWindowHeight / g_uiComputeThreadGroupSize + (uiWindowHeight % g_uiComputeThreadGroupSize != 0 ? 1 : 0)).IgnoreResult();

      renderContext.EndCompute();
    }

    // Draw histogram.
    {
      xiiGALRenderingSetup renderingSetup;
      renderingSetup.m_RenderTargetSetup.SetRenderTarget(0, hBackbufferRTV);
      renderContext.BeginRendering(pGALPass, renderingSetup, viewport, "DrawHistogram");

      renderContext.BindShader(m_hHistogramDisplayShader);
      renderContext.BindMeshBuffer(m_hHistogramQuadMeshBuffer);
      renderContext.BindTexture2D("HistogramTexture", m_hHistogramSRV);
      renderContext.DrawMeshBuffer().IgnoreResult();

      renderContext.EndRendering();
    }

    device->EndPass(pGALPass);

    device->EndPipeline(m_hSwapChain);

    device->EndFrame();

    xiiRenderContext::GetDefaultInstance()->ResetContextState();
  }

  // Needs to be called once per frame
  xiiResourceManager::PerFrameUpdate();

  // Tell the task system to finish its work for this frame
  // This has to be done at the very end, so that the task system will only use up the time that is left in this frame for
  // uploading GPU data etc.
  xiiTaskSystem::FinishFrameTasks();

  return WasQuitRequested() ? xiiApplication::Execution::Quit : xiiApplication::Execution::Continue;
}

void xiiComputeShaderHistogramApp::AfterCoreSystemsStartup()
{
  xiiGraphicsDevice::Default = xiiGraphicsDevice::Vulkan;

  SUPER::AfterCoreSystemsStartup();

  m_pDirectoryWatcher = XII_DEFAULT_NEW(xiiDirectoryWatcher);
  XII_VERIFY(m_pDirectoryWatcher->OpenDirectory(FindProjectDirectory(), xiiDirectoryWatcher::Watch::Writes | xiiDirectoryWatcher::Watch::Subdirectories).Succeeded(), "Failed to watch project directory");

  auto device = xiiGALDevice::GetDefaultDevice();

  // Retrieve window and swapchain handle for rendering
  {
    xiiHybridArray<xiiActor*, 8> allActors;
    xiiActorManager::GetSingleton()->GetAllActors(allActors);

    for (xiiActor* pActor : allActors)
    {
      xiiActorPluginWindow* pWindowPlugin = pActor->GetPlugin<xiiActorPluginWindow>();

      if (pWindowPlugin == nullptr)
        continue;

      m_pWindow = pWindowPlugin->GetWindow();

      // Retrieve only the first output target
      if (auto pOutput = pWindowPlugin->GetOutputTarget())
      {
        m_hSwapChain = static_cast<xiiWindowOutputTargetGAL*>(pOutput)->m_hSwapChain;
      }
    }
  }

  // Create textures and texture view for screen content (can't use back-buffer as shader resource view)
  {
    xiiGALTextureCreationDescription texDesc;
    texDesc.m_uiWidth                  = m_pWindow->GetClientAreaSize().width;
    texDesc.m_uiHeight                 = m_pWindow->GetClientAreaSize().height;
    texDesc.m_Format                   = xiiGALResourceFormat::RGBAUByteNormalized; // xiiGALResourceFormat::RGBAUByteNormalizedsRGB;
    texDesc.m_bCreateRenderTarget      = true;
    texDesc.m_bAllowShaderResourceView = true;

    m_hScreenTexture = device->CreateTexture(texDesc);
    m_hScreenRTV     = device->GetDefaultRenderTargetView(m_hScreenTexture);
    m_hScreenSRV     = device->GetDefaultResourceView(m_hScreenTexture);
  }

  // Create texture for histogram data.
  {
    xiiGALTextureCreationDescription texDesc;
    texDesc.m_uiWidth                     = 256;
    texDesc.m_uiHeight                    = 3; // R, G, B
    texDesc.m_uiMipLevelCount             = 1;
    texDesc.m_Format                      = xiiGALResourceFormat::RUInt;
    texDesc.m_bCreateRenderTarget         = false;
    texDesc.m_bAllowShaderResourceView    = true;
    texDesc.m_bAllowUAV                   = true;
    texDesc.m_ResourceAccess.m_bImmutable = false;

    m_hHistogramTexture = device->CreateTexture(texDesc);
    m_hHistogramSRV     = device->GetDefaultResourceView(m_hHistogramTexture);

    xiiGALUnorderedAccessViewCreationDescription uavDesc;
    uavDesc.m_hTexture = m_hHistogramTexture;
    m_hHistogramUAV    = device->CreateUnorderedAccessView(uavDesc);
  }

  // Setup Shaders and Materials
  {
    m_hScreenShader           = xiiResourceManager::LoadResource<xiiShaderResource>("Shaders/screen.xiiShader");
    m_hHistogramComputeShader = xiiResourceManager::LoadResource<xiiShaderResource>("Shaders/histogramcompute.xiiShader");
    m_hHistogramDisplayShader = xiiResourceManager::LoadResource<xiiShaderResource>("Shaders/histogramdisplay.xiiShader");
  }

  // Geometry.
  CreateHistogramQuad();
}

void xiiComputeShaderHistogramApp::BeforeHighLevelSystemsShutdown()
{
  auto device = xiiGALDevice::GetDefaultDevice();

  m_hScreenShader.Invalidate();
  m_hHistogramDisplayShader.Invalidate();
  m_hHistogramComputeShader.Invalidate();
  m_hHistogramQuadMeshBuffer.Invalidate();

  m_hScreenRTV.Invalidate();
  m_hScreenSRV.Invalidate();
  device->DestroyTexture(m_hScreenTexture);
  m_hScreenTexture.Invalidate();
  device->DestroySwapChain(m_hSwapChain);

  device->DestroyUnorderedAccessView(m_hHistogramUAV);
  m_hHistogramUAV.Invalidate();
  m_hHistogramSRV.Invalidate();
  device->DestroyTexture(m_hHistogramTexture);
  m_hHistogramTexture.Invalidate();

  SUPER::BeforeHighLevelSystemsShutdown();
}

void xiiComputeShaderHistogramApp::CreateHistogramQuad()
{
  m_hHistogramQuadMeshBuffer = xiiResourceManager::GetExistingResource<xiiMeshBufferResource>("{4BEFA142-FEDB-42D0-84DC-58223ADD8C62}");

  if (!m_hHistogramQuadMeshBuffer.IsValid())
  {
    xiiVec2     pixToScreen(1.0f / m_pWindow->GetClientAreaSize().width * 0.5f, 1.0f / m_pWindow->GetClientAreaSize().height * 0.5f);
    const float borderOffsetPix = 80.0f;
    const float sizeScreen      = 0.8f;

    xiiGeometry             geom;
    xiiGeometry::GeoOptions opt;
    opt.m_Color     = xiiColor::Black;
    opt.m_Transform = xiiMat4(xiiMat3::IdentityMatrix(), xiiVec3(1.0f - pixToScreen.x * borderOffsetPix - sizeScreen / 2, -1.0f + pixToScreen.y * borderOffsetPix + sizeScreen / 2, 0.0f));
    geom.AddRectXY(xiiVec2(sizeScreen, sizeScreen), 1, 1, opt);

    xiiMeshBufferResourceDescriptor desc;
    desc.AddStream(xiiGALVertexAttributeSemantic::Position, xiiGALResourceFormat::XYZFloat);
    desc.AddStream(xiiGALVertexAttributeSemantic::TexCoord0, xiiGALResourceFormat::XYFloat);
    desc.AllocateStreamsFromGeometry(geom);

    xiiUInt32 t = 0;
    for (xiiUInt32 p = 0; p < geom.GetPolygons().GetCount(); ++p)
    {
      for (xiiUInt32 v = 0; v < geom.GetPolygons()[p].m_Vertices.GetCount() - 2; ++v)
      {
        desc.SetTriangleIndices(t, geom.GetPolygons()[p].m_Vertices[0], geom.GetPolygons()[p].m_Vertices[v + 1], geom.GetPolygons()[p].m_Vertices[v + 2]);

        ++t;
      }
    }

    m_hHistogramQuadMeshBuffer = xiiResourceManager::GetOrCreateResource<xiiMeshBufferResource>("{4BEFA142-FEDB-42D0-84DC-58223ADD8C62}", std::move(desc));
  }
}

void xiiComputeShaderHistogramApp::OnFileChanged(const char* filename, xiiDirectoryWatcherAction action, xiiDirectoryWatcherType type)
{
  if (action == xiiDirectoryWatcherAction::Modified && type == xiiDirectoryWatcherType::File)
  {
    xiiLog::Info("File {0} modified.", filename);
    m_bDirectoryModified = true;
  }
}

XII_CONSOLEAPP_ENTRY_POINT(xiiComputeShaderHistogramApp);
