#pragma once

#include <EditorFramework/EditorFrameworkDLL.h>

#include <Foundation/Reflection/Implementation/StaticRTTI.h>
#include <Foundation/Strings/HashedString.h>
#include <Foundation/Strings/String.h>
#include <Foundation/Time/Timestamp.h>
#include <Foundation/Types/Bitflags.h>
#include <Foundation/Types/Uuid.h>

class xiiImage;
class xiiAssetFileHeader;

struct xiiAssetExistanceState
{
  using StorageType = xiiUInt8;

  enum Enum : xiiUInt8
  {
    FileAdded,
    FileRemoved,
    FileMoved,
    FileModified,
    FileUnchanged,
  };
};

struct xiiAssetDocumentFlags
{
  using StorageType = xiiUInt8;

  enum Enum
  {
    None                              = 0,
    AutoTransformOnSave               = XII_BIT(0), ///< Every time the document is saved, TransformAsset is automatically executed
    DisableTransform                  = XII_BIT(1), ///< If set, TransformAsset will not do anything
    OnlyTransformManually             = XII_BIT(2), ///< The asset transformation is not done, unless explicitly requested for this asset
    SupportsThumbnail                 = XII_BIT(3), ///< The asset supports thumbnail generation (InternalCreateThumbnail must be implemented).
    AutoThumbnailOnTransform          = XII_BIT(4), ///< Thumbnail is automatically generated by the asset transform, and does not need to be explicitly created.
    SubAssetsSupportThumbnail         = XII_BIT(5), ///< The sub-asset supports thumbnail generation (InternalCreateThumbnail must be implemented).
    SubAssetsAutoThumbnailOnTransform = XII_BIT(6), ///< Thumbnails for sub-assets are automatically generated by the asset transform, and do not need to be explicitly created.
    Default                           = None
  };

  struct Bits
  {
    StorageType AutoTransformOnSave : 1;
    StorageType DisableTransform : 1;
    StorageType OnlyTransformManually : 1;
    StorageType SupportsThumbnail : 1;
    StorageType AutoThumbnailOnTransform : 1;
  };
};

XII_DECLARE_FLAGS_OPERATORS(xiiAssetDocumentFlags);

struct xiiTransformFlags
{
  using StorageType = xiiUInt8;

  enum Enum
  {
    None              = 0,
    TriggeredManually = XII_BIT(0),    ///< Transform triggered by user directly. Needs to be set to transform assets marked with
                                       ///< xiiAssetDocumentFlags::Enum::OnlyTransformManually.
    ForceTransform       = XII_BIT(1), ///< Will transform the asset regardless of its current transform state.
    BackgroundProcessing = XII_BIT(2), ///< If changes need to be made that requires re-saving the asset transform will be aborted and xiiTransformResult::NeedsImport is returned.
    Default              = None
  };

  struct Bits
  {
    StorageType TriggeredManually : 1;
    StorageType ForceTransform : 1;
    StorageType BackgroundProcessing : 1;
  };
};
XII_DECLARE_FLAGS_OPERATORS(xiiTransformFlags);

struct xiiSubAssetData
{
  xiiUuid         m_Guid;
  xiiHashedString m_sSubAssetsDocumentTypeName;
  xiiString       m_sName;
};

struct XII_EDITORFRAMEWORK_DLL xiiAssetDocumentTypeDescriptor : public xiiDocumentTypeDescriptor
{
  xiiAssetDocumentTypeDescriptor()  = default;
  ~xiiAssetDocumentTypeDescriptor() = default;

  xiiString                          m_sResourceFileExtension;
  xiiBitflags<xiiAssetDocumentFlags> m_AssetDocumentFlags;
};


struct xiiTransformResult
{
  using StorageType = xiiUInt8;

  enum Enum : xiiUInt8
  {
    Success = 0,
    Failure,
    NeedsImport,
    Default = Success,
  };
};
XII_DECLARE_REFLECTABLE_TYPE(XII_EDITORFRAMEWORK_DLL, xiiTransformResult);


struct XII_EDITORFRAMEWORK_DLL xiiTransformStatus
{
  XII_ALWAYS_INLINE explicit xiiTransformStatus() :
    m_Result(xiiTransformResult::Success)
  {
  }

  explicit xiiTransformStatus(const char* szError) :
    m_Result(xiiTransformResult::Failure), m_sMessage(szError)
  {
  }

  explicit xiiTransformStatus(xiiTransformResult::Enum r, xiiStringView sError) :
    m_Result(r), m_sMessage(sError)
  {
  }

  explicit xiiTransformStatus(xiiStringView sError) :
    m_Result(xiiTransformResult::Failure), m_sMessage(sError)
  {
  }

  XII_ALWAYS_INLINE xiiTransformStatus(xiiTransformResult::Enum r) :
    m_Result(r)
  {
  }

  XII_ALWAYS_INLINE xiiTransformStatus(xiiStatus r) :
    m_Result(r.Succeeded() ? xiiTransformResult::Success : xiiTransformResult::Failure), m_sMessage(r.m_sMessage)
  {
  }

  XII_ALWAYS_INLINE xiiTransformStatus(xiiResult r) :
    m_Result(r.Succeeded() ? xiiTransformResult::Success : xiiTransformResult::Failure)
  {
  }

  explicit xiiTransformStatus(const xiiFormatString& fmt) :
    m_Result(xiiTransformResult::Failure)
  {
    xiiStringBuilder sMsg;
    m_sMessage = fmt.GetText(sMsg);
  }

  XII_ALWAYS_INLINE bool Succeeded() const { return m_Result == xiiTransformResult::Success; }
  XII_ALWAYS_INLINE bool Failed() const { return m_Result == xiiTransformResult::Failure; }

  xiiEnum<xiiTransformResult> m_Result;
  xiiString                   m_sMessage;
};
XII_DECLARE_REFLECTABLE_TYPE(XII_EDITORFRAMEWORK_DLL, xiiTransformStatus);

XII_ALWAYS_INLINE xiiResult xiiToResult(const xiiTransformStatus& result)
{
  return result.m_Result == xiiTransformResult::Success ? XII_SUCCESS : XII_FAILURE;
}
