#include <Foundation/FoundationPCH.h>

#if XII_ENABLED(XII_PLATFORM_WINDOWS_DESKTOP)

#elif XII_ENABLED(XII_PLATFORM_WINDOWS_UWP)

#elif XII_ENABLED(XII_PLATFORM_LINUX)

#elif XII_ENABLED(XII_PLATFORM_OSX)

#elif XII_ENABLED(XII_PLATFORM_ANDROID)

#endif
