#include <GraphicsCore/GraphicsCorePCH.h>

#include <GraphicsCore/Pipeline/Passes/PerFrameBufferUploadPass.h>
#include <GraphicsCore/Pipeline/RenderGraph.h>
#include <GraphicsCore/Pipeline/View.h>
#include <GraphicsFoundation/Device/Device.h>

// clang-format off
XII_BEGIN_DYNAMIC_REFLECTED_TYPE(xiiPerFrameBufferUploadPass, 1, xiiRTTIDefaultAllocator<xiiPerFrameBufferUploadPass>)
{
  XII_BEGIN_PROPERTIES
  {
    XII_MEMBER_PROPERTY("Active", m_bActive)->AddAttributes(new xiiDefaultValueAttribute(true)),
    XII_MEMBER_PROPERTY("Name", m_sName)->AddAttributes(new xiiDefaultValueAttribute("PerFrameBufferUploadPass")),
  }
  XII_END_PROPERTIES;
}
XII_END_DYNAMIC_REFLECTED_TYPE;
// clang-format on

xiiPerFrameBufferUploadPass::xiiPerFrameBufferUploadPass() : xiiRenderPipelinePass("PerFrameBufferUploadPass")
{
}

xiiPerFrameBufferUploadPass::~xiiPerFrameBufferUploadPass()
{
  m_pPerFrameBuffer.Clear();
}

namespace
{
  struct UploadPassData
  {
    xiiRGBufferHandle    m_hBuffer;
    xiiPerFrameConstants m_Constants; // We store it explicitly so the lambda closure copies it
  };
}

void xiiPerFrameBufferUploadPass::AddToGraph(xiiView& view, xiiRenderGraph& graph, xiiRenderGraphBlackboard& blackboard)
{
  if (!m_pPerFrameBuffer)
  {
    xiiGALBufferCreationDescription desc;
    desc.m_uiSize        = sizeof(xiiPerFrameConstants);
    desc.m_BufferFlags   = xiiGALBufferUsageFlags::ConstantBuffer;
    desc.m_ResourceUsage = xiiGALResourceUsage::Dynamic;

    m_pPerFrameBuffer = xiiGALDevice::GetDefaultDevice()->CreateBuffer(desc);
  }

  // Retrieve values from the Blackboard generated by previous passes.
  float fResolutionScale = 1.0f;
  blackboard.TryGet(xiiMakeHashedString("DynamicResolutionScale"), fResolutionScale);

  // Read view data.
  const xiiViewData& viewData = view.GetData();
  
  // Fill constants safely on the main thread
  xiiPerFrameConstants constants;
  constants.m_ViewMatrix              = viewData.m_ViewMatrix[0];
  constants.m_ProjectionMatrix        = viewData.m_ProjectionMatrix[0];
  constants.m_ViewProjectionMatrix    = viewData.m_ViewProjectionMatrix[0];
  constants.m_CameraPosition          = viewData.m_InverseViewMatrix[0].GetTranslationVector(); // Just the translation of the inv-view matrix works as rough position
  constants.m_fDynamicResolutionScale = fResolutionScale;

  auto [pData, hPass] = graph.AddPass<UploadPassData>(
    GetName(),
    xiiGALCommandQueueFlags::Graphics, // Typically update goes on transfer or graphics queue
    [this](UploadPassData& data, xiiRGBuilder& builder)
    {
      data.m_hBuffer = builder.ImportBuffer("PerFrameConstantBuffer", m_pPerFrameBuffer, xiiGALResourceStateFlags::ConstantBuffer);
      
      // Let the graph know we are writing to this imported buffer to secure states.
      data.m_hBuffer = builder.WriteBuffer(data.m_hBuffer, xiiGALResourceStateFlags::CopyDestination);
      
      builder.SetPassSideEffects(true);
      builder.SetPassAllowMerge(false);
    },
    [constants](const UploadPassData& data, xiiRGPassContext& context)
    {
       xiiGALCommandList& cmd = context.GetCommandList();
       xiiGALBuffer* pTargetBuffer = context.GetBuffer(data.m_hBuffer);
       
       cmd.UpdateBuffer(pTargetBuffer, 0, &constants, sizeof(xiiPerFrameConstants));
    }
  );
}
