#include <JoltPlugin/JoltPluginPCH.h>

XII_STATICLINK_LIBRARY(JoltPlugin)
{
  if (bReturn)
    return;

  XII_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltActorComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltDynamicActorComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltQueryShapeActorComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltStaticActorComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Actors_Implementation_JoltTriggerComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltCharacterControllerComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Character_Implementation_JoltDefaultCharacterComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltBoneColliderComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRagdollComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltRopeComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltSettingsComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Components_Implementation_JoltVisColMeshComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_Jolt6DOFConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConeConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltDistanceConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltFixedConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltGrabObjectComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltHingeConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltPointConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSliderConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Constraints_Implementation_JoltSwingTwistConstraintComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Resources_JoltMeshResource);
  XII_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltCustomShapeInfo);
  XII_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeBoxComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCapsuleComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeConvexHullComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeCylinderComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Shapes_Implementation_JoltShapeSphereComponent);
  XII_STATICLINK_REFERENCE(JoltPlugin_Startup);
  XII_STATICLINK_REFERENCE(JoltPlugin_System_JoltCollisionFiltering);
  XII_STATICLINK_REFERENCE(JoltPlugin_System_JoltContacts);
  XII_STATICLINK_REFERENCE(JoltPlugin_System_JoltCore);
  XII_STATICLINK_REFERENCE(JoltPlugin_System_JoltDebugRenderer);
  XII_STATICLINK_REFERENCE(JoltPlugin_System_JoltQueries);
  XII_STATICLINK_REFERENCE(JoltPlugin_System_JoltWorldModule);
}
