# Copyright (c) Theophilus Eriata. All Rights Reserved.

set_property(GLOBAL PROPERTY XII_CMAKE_PLATFORM_POSIX OFF)
set_property(GLOBAL PROPERTY XII_CMAKE_PLATFORM_SUPPORTS_EDITOR OFF)
set_property(GLOBAL PROPERTY XII_CMAKE_PLATFORM_SUPPORTS_VULKAN OFF)
set_property(GLOBAL PROPERTY XII_CMAKE_PLATFORM_SUPPORTS_D3D12 OFF)
