if(APPLE OR CMAKE_SYSTEM_NAME STREQUAL "Darwin" OR (DEFINED CURRENT_OSX_VERSION AND NOT "${CURRENT_OSX_VERSION}" STREQUAL ""))
  if(NOT DEFINED CURRENT_OSX_VERSION OR "${CURRENT_OSX_VERSION}" STREQUAL "")
    # Ensure other CMake files can test for OSX using this variable.
    set(CURRENT_OSX_VERSION 1 CACHE INTERNAL "Detected macOS")
  endif()

  set_property(GLOBAL PROPERTY XII_CMAKE_PLATFORM_NAME "OSX")
  set_property(GLOBAL PROPERTY XII_CMAKE_PLATFORM_PREFIX "OSX")
  set_property(GLOBAL PROPERTY XII_CMAKE_PLATFORM_POSTFIX "OSX")
endif()
