name: ClangTidy

on:
  pull_request:
    branches: [ Development ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Run ClangTidy
        id: lint_files
        shell: pwsh
        run: |
          echo "::set-output name=push::false"

          git fetch origin "${env:GITHUB_HEAD_REF}:refs/remotes/origin/${env:GITHUB_HEAD_REF}"

          git checkout --track "origin/${env:GITHUB_HEAD_REF}"

          git submodule update --init --remote Data/Tools/Precompiled

          echo "Download LLVM and CMake"

          Invoke-WebRequest https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.3/LLVM-15.0.3-win64.exe -OutFile "LLVM-15.0.3-win64.exe"

          & ${env:GITHUB_WORKSPACE}/Data/Tools/Precompiled/7z.exe x -ollvm LLVM-15.0.3-win64.exe

          $WindowsSdkVersion = ((Get-ChildItem -Directory "C:\Program Files (x86)\Windows Kits\10\bin").Name | ? { $_ -match "^10\.0\." } | sort -Descending)[0]

          Write-Host "Windows SDK Found" $WindowsSdkVersion

          $srcExe = "C:\Program Files (x86)\Windows Kits\10\bin\$WindowsSdkVersion\x64\rc.exe" -replace "\\","/"
          $clangCppExe = "$pwd\llvm\bin\clang++.exe" -replace "\\","/"
          $clangExe = "$pwd\llvm\bin\clang.exe" -replace "\\","/"

          & ${env:GITHUB_WORKSPACE}/Data/Tools/Precompiled/cmake/bin/cmake.exe -G Ninja -B workspace-clang -S . "-DCMAKE_CXX_COMPILER=$clangCppExe" "-DCMAKE_C_COMPILER=$clangExe" "-DCMAKE_RC_COMPILER=$srcExe" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DXII_USE_PCH=OFF -DXII_ENABLE_FOLDER_UNITY_FILES=OFF

          echo "Running ClangTidy"

          & ${env:GITHUB_WORKSPACE}/Utilities/RunClangTidy.ps1 -DiffTo "${env:GITHUB_BASE_REF}" -LlvmInstallDir "$pwd\llvm" -Workspace "workspace-clang"

          # Write out patch file.
          # Changes done by ClangTidy on MemberProperty.h are always incorrect.
          git checkout "Source/Engine/Foundation/Reflection/Implementation/MemberProperty.h"
          if(@(git status -s --untracked-files=no).Length -gt 0)
          {
            Write-Host "##vso[task.logissue type=error]ClangTidy suggested changes. ClangTidy check failed! See artifact 'clangTidy.patch' for suggested changes. Apply patch with: git apply clangTidy.patch" -foreground red
            git diff | Out-File -Encoding utf8NoBOM -FilePath "${env:GITHUB_WORKSPACE}/clangTidy.patch"

            echo "::set-output name=push::true"
          }
          else
          {
            echo "ClangTidy checks passed. No changes necessary."
          }

      - name: Content of Patch
        if: ${{ steps.lint_files.outputs.push == 'true' }}
        shell: pwsh
        run: |
          Get-Content -Path "${env:GITHUB_WORKSPACE}/clangTidy.patch"

      - name: Upload Patch File
        if: ${{ steps.lint_files.outputs.push == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: ClangFormatPatch
          path: ${{github.workspace}}/clangTidy.patch
          retention-days: 3
