name: Auto Label Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  auto-label:
    name: Label PRs Based on File Paths
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github

      - name: Run Labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.API_TOKEN_GITHUB }}
          configuration-path: ${{ github.workspace }}/.github/labeler.yml
          sync-labels: true
